// Popular vegetarian dishes, Indian and international, for building a library quickly.
// Ingredient names use everyday Indian-kitchen names (capsicum, maida, besan…) so they
// line up with what people track in the Kitchen tab.

import { recipeFor } from './recipes.js';

const MEALS = { B: 'breakfast', L: 'lunch', D: 'dinner' };

// A recipe video for each dish: [YouTube id, channel, title]. Picked from the recommended creators
// (see creators.js) where one had a full-length video of this dish, otherwise a well-viewed vegetarian one.
const VIDEOS = {
  'Palak Paneer': ['5lVLxEr_qgM', 'Ranveer Brar', 'Palak Paneer recipe'],
  'Paneer Butter Masala': ['a30BLUQiFoc', 'Ranveer Brar', 'Paneer Butter Masala, restaurant style'],
  'Matar Paneer': ['y05q2kYkBDA', 'Nisha Madhulika', 'Matar Paneer: easy and quick'],
  'Kadai Paneer': ['nRPmoioNisI', 'Ranveer Brar', 'Kadhai Paneer recipe'],
  'Paneer Bhurji': ['clQ1oKSTjqo', 'Kabita’s Kitchen', 'Street-style Paneer Bhurji'],
  'Malai Kofta': ['JKNXj6Hp8gA', 'Ranveer Brar', 'Malai Kofta curry'],
  'Dal Tadka': ['3XTSCbZfEgM', 'Ranveer Brar', 'Dhaba-style Dal Fry / Dal Tadka'],
  'Dal Makhani': ['mA5XjhdwJHc', 'Ranveer Brar', 'Dal Makhani, dhaba style'],
  'Rajma Chawal': ['M_ncAJhIaIU', 'Kunal Kapur', 'Rajma Chawal, Punjabi style'],
  'Chole': ['j-ucNH4rGC0', 'Kunal Kapur', 'Shaadi-wale Pindi Chole'],
  'Kadhi Pakora': ['Zk3pddws0Lg', 'Nisha Madhulika', 'Pakoda Kadhi with tips'],
  'Aloo Gobi': ['Iv-qfNzO6qQ', 'Nisha Madhulika', 'Aloo Gobhi, party style, less oil'],
  'Aloo Matar': ['oVfWo91JoSM', 'Nisha Madhulika', 'Aloo Matar curry'],
  'Bhindi Masala': ['l8Hjg3jKOU0', 'Nisha Madhulika', 'Bhindi Masala, restaurant style'],
  'Baingan Bharta': ['yRZKfDI28Ro', 'Ranveer Brar', 'Baingan Bharta, dhaba style'],
  'Mix Veg': ['ilJtXpdzj7s', 'Nisha Madhulika', 'Mixed Vegetable, restaurant style'],
  'Aloo Paratha': ['Azw4jxvj5Jo', 'bharatzkitchen', 'Punjabi stuffed Aloo Paratha'],
  'Besan Chilla': ['h9cJLV-EMbA', 'Nisha Madhulika', 'Mixed veg Besan Cheela'],
  'Moong Dal Khichdi': ['9C0MvVKCXAE', 'Nisha Madhulika', 'Moong Dal Khichdi'],
  'Jeera Rice': ['Y8yEn08h-q0', 'Kabita’s Kitchen', 'Restaurant-style Jeera Rice in a cooker'],
  'Veg Pulao': ['qFE9madv0RY', 'Kabita’s Kitchen', 'Veg Pulao in a pressure cooker'],
  'Veg Biryani': ['GridojtCXDE', 'Vahchef', 'Vegetable Biryani, traditional'],
  'Pav Bhaji': ['Gbuse4WX01I', 'Your Food Lab', 'Street-style Pav Bhaji'],
  'Poha': ['VKvwWeVy8Nw', 'Kabita’s Kitchen', 'Kanda Poha'],
  'Methi Thepla': ['mFTfjVOQEkI', 'Nisha Madhulika', 'Gujarati Methi Thepla'],
  'Dhokla': ['6R40KFQmOAo', 'Nisha Madhulika', 'Soft, spongy instant Dhokla: tips & tricks'],
  'Masala Dosa': ['0JF8RfBSFRk', 'Hebbars Kitchen', 'Hotel-style Masala Dosa'],
  'Idli Sambar': ['nIoIzarlQ1k', 'Hebbars Kitchen', 'Idli Sambar (tiffin sambar)'],
  'Sambar Rice': ['NQpnf7M5K7Y', 'Hebbars Kitchen', 'Hotel-style Sambar Rice'],
  'Upma': ['W4mnN7Fcaz0', 'Kabita’s Kitchen', 'Rava Upma'],
  'Margherita Pizza': ['xdshDFwu9x4', 'Yum Curry', 'Pizza Margherita, with the dough'],
  'Penne Arrabbiata': ['blIm1ezy_UA', 'Your Food Lab', 'Pasta in arrabbiata (red) sauce'],
  'Pesto Pasta': ['-WXdkJEJ4kE', 'Your Food Lab', 'Pesto Pasta'],
  'Aglio e Olio': ['sKmDN_dU5Cw', 'Your Food Lab', 'Aglio e Olio in 10 minutes'],
  'Mushroom Risotto': ['u93NfkAmOyo', 'Rainbow Plant Life', 'Vegan Mushroom Risotto'],
  'Veg Lasagne': ['LLWqK4cgki8', 'Your Food Lab', 'Veg Lasagna, no oven'],
  'Minestrone Soup': ['4sWBtdXLEMM', 'Rajshri Food', 'Minestrone Soup, vegetarian'],
  'Tomato Basil Soup': ['W88m7LKFR9s', 'Your Food Lab', 'Tomato Basil Soup'],
  'Mac and Cheese': ['GGsf51oW7V8', 'Ethan Chlebowski', 'Stovetop Mac and Cheese'],
  'Greek Salad': ['kwq4vl610iY', 'Preppy Kitchen', 'Easy Greek Salad'],
  'Falafel & Hummus': ['AIczG0gl1-I', 'Your Food Lab', 'Falafel and Hummus'],
  'Veg Burrito Bowl': ['v3FGarkITTQ', 'Your Food Lab', 'Veg Mexican Burrito Bowl'],
  'Cheese Quesadilla': ['AhoZ2TbLxzU', 'HomeCookingShow', 'Veg Cheese Quesadilla'],
  'Thai Green Curry': ['-zeV6vSS0mk', 'Your Food Lab', 'Veg Thai Green Curry, with homemade paste'],
  'Veg Pad Thai': ['zy_P70hXhdM', 'Yeung Man Cooking', 'Vegetarian Pad Thai'],
  'Veg Katsu Curry': ['Gen_w-ByWCs', 'Gaz Oakley', 'Katsu Curry (vegan)'],
  'Tofu Stir-fry': ['ioCJLUSeTiM', 'Meghna’s Food Magic', 'Stir-fry Vegetables with Tofu'],
  'Veg Hakka Noodles': ['4Q12_scB6AY', 'Your Food Lab', 'Hakka Noodles, hotel style'],
  'Veg Fried Rice': ['1WQVzQBNk_Q', 'Your Food Lab', 'Veg Fried Rice, restaurant style'],
  'Chilli Paneer': ['fPyHXiHbLg4', 'Your Food Lab', 'Chilli Paneer, restaurant style'],
  'Veg Manchurian': ['6K8ZJG6cQ2U', 'Your Food Lab', 'Veg Manchurian (dry)'],
  // Added later (30 more).
  'Shahi Paneer': ['inVClSNYBQ4', 'Ranveer Brar', 'Dhaba-style Shahi Paneer'],
  'Dum Aloo': ['RFvfvR_Julk', 'Ranveer Brar', 'Hyderabadi Dum Aloo'],
  'Methi Malai Matar': ['maxiwdeTu68', 'Ranveer Brar', 'Methi Matar Malai'],
  'Sarson ka Saag': ['-yhf5fx6LQM', 'Ranveer Brar', 'Punjabi Sarson ka Saag'],
  'Chana Dal Fry': ['VoV7b7XtS2E', 'Kunal Kapur', 'Dhaba-style Chana Dal Fry'],
  'Kala Chana Masala': ['YAsHnMjd0PE', 'Kabita’s Kitchen', 'Dhaba-style Kala Chana Masala'],
  'Lauki Chana Dal': ['hq0ed55i1_Y', 'Kabita’s Kitchen', 'Bihari-style Lauki Chana Dal'],
  'Gobi Paratha': ['1kGQIs7fycA', 'Kabita’s Kitchen', 'Gobi Paratha'],
  'Paneer Paratha': ['w1B2PuRKJJU', 'Kunal Kapur', 'Paneer Paratha'],
  'Gatte ki Sabzi': ['Z_SZ44sqI4E', 'Nisha Madhulika', 'Besan Gatte ki Sabzi'],
  'Aloo Posto': ['BI1v4Y8Td_M', 'Bong Eats', 'Aloo Posto: tips and tricks'],
  'Cholar Dal': ['MtcAg-5SeT8', 'Bong Eats', 'Cholar Dal with coconut and raisins'],
  'Mirchi ka Salan': ['MuB2diQ_Bq4', 'Vahchef', 'Mirchi ka Salan'],
  'Medu Vada': ['DwiDbLfHnjI', 'Vahchef', 'Medu Vada'],
  'Lemon Rice': ['bNq4OPjUiic', 'Vahchef', 'Lemon Rice'],
  'Bisi Bele Bath': ['QFIXE88KCrk', 'Vahchef', 'Bisi Bele Bath'],
  'Avial': ['0L0xUfagiHQ', 'Vahchef', 'Avial'],
  'Vada Pav': ['r4saZD0J_gU', 'Your Food Lab', 'Vada Pav with dry garlic chutney'],
  'Misal Pav': ['gJXeu2Eih60', 'Your Food Lab', 'Misal Pav'],
  'Paneer Kathi Roll': ['Wb95nUQZLXM', 'Your Food Lab', 'Paneer Kathi Roll'],
  'White Sauce Pasta': ['CHUYtrCtre4', 'Your Food Lab', 'White Sauce Pasta (also red and pink)'],
  'Veg Khao Suey': ['5g3dMgCyil4', 'Your Food Lab', 'Veg Burmese Khao Suey'],
  'Thai Red Curry': ['GWBxYDLRpD8', 'Your Food Lab', 'Veg Thai Red Curry, with homemade paste'],
  'Veg Spring Rolls': ['-gOhyN8WJMY', 'Your Food Lab', 'Veg Spring Rolls, with homemade sheets'],
  'Schezwan Fried Rice': ['suXQ2mPfhSg', 'Your Food Lab', 'Veg Schezwan Fried Rice'],
  'Hot and Sour Soup': ['1ltR8xVvg_w', 'Your Food Lab', 'Veg Hot & Sour Soup'],
  'Sweet Corn Soup': ['BVDxruxmQy4', 'Your Food Lab', 'Veg Sweet Corn Soup with fresh corn'],
  'Paneer Tikka Tacos': ['QSZR1DUgnfs', 'Your Food Lab', 'Paneer Tikka Masala Tacos'],
  'Potato Au Gratin': ['KGWgJMa2_jQ', 'Sanjeev Kapoor Khazana', 'Potato Au Gratin'],
  'Bruschetta': ['c-Q5PpPQJWM', 'Sanjeev Kapoor Khazana', 'Bruschetta'],
  // Not in the veg catalogue, but in the sample data (archived).
  'Masala Omelette': ['sAa-CEl5Z-k', 'Ranveer Brar', 'Masala Omelette'],
  'Shakshuka': ['4_NjuSgOV6Y', 'Your Food Lab', 'Indian-style Shakshuka'],
};
const VIDEO_BY_KEY = new Map(Object.entries(VIDEOS).map(([name, v]) => [name.toLowerCase().trim(), v]));

/** A dish's `links` and `linkInfo` fields for its catalogue video (empty if there isn't one). */
export function videoFields(dishName) {
  const v = VIDEO_BY_KEY.get(String(dishName || '').toLowerCase().trim());
  if (!v) return { links: [], linkInfo: {} };
  const url = `https://www.youtube.com/watch?v=${v[0]}`;
  return { links: [url], linkInfo: { [url]: { title: v[2], channel: v[1] } } };
}

/** dish(name, cuisine, meals as "BLD" letters, minutes, "Ingredient|qty; …" (or null when recipes.js has it), tags) */
const dish = (region, name, cuisine, meals, cookTime, ingredients, tags = []) => ({
  region,
  name,
  cuisine,
  meals: [...meals].map((m) => MEALS[m]),
  cookTime,
  ingredients: (ingredients || '').split(';').filter((x) => x.trim()).map((x) => {
    const [n, qty = ''] = x.split('|').map((t) => t.trim());
    return { name: n, qty };
  }),
  tags,
  diet: 'veg',
  method: [],
  recipeFrom: '',
  ...videoFields(name),
  // Where we've checked the video, its ingredients and method replace the generic list above.
  ...recipeFor(name),
});
const indian = (...a) => dish('indian', ...a);
const world = (...a) => dish('international', ...a);

export const CATALOG = [
  // ---- Indian ----
  indian('Palak Paneer', 'North Indian', 'LD', 40, 'Spinach|2 bunches; Paneer|200 g; Onion|1; Tomato|2; Ginger garlic paste|1 tbsp; Green chilli|2; Cream|2 tbsp; Garam masala|½ tsp; Cumin seeds|1 tsp', ['high protein']),
  indian('Paneer Butter Masala', 'North Indian', 'LD', 40, 'Paneer|250 g; Tomato|4; Butter|2 tbsp; Cashews|10; Cream|3 tbsp; Kasuri methi|1 tsp; Ginger garlic paste|1 tbsp; Garam masala|½ tsp', ['rich']),
  indian('Matar Paneer', 'North Indian', 'LD', 35, 'Paneer|200 g; Peas|1 cup; Onion|2; Tomato|2; Ginger garlic paste|1 tbsp; Garam masala|½ tsp'),
  indian('Kadai Paneer', 'North Indian', 'LD', 30, 'Paneer|200 g; Capsicum|2; Onion|2; Tomato|2; Kadai masala|2 tsp; Coriander leaves|handful'),
  indian('Paneer Bhurji', 'North Indian', 'BD', 20, 'Paneer|200 g; Onion|1; Tomato|1; Capsicum|½; Green chilli|1; Coriander leaves|handful', ['quick', 'high protein']),
  indian('Malai Kofta', 'North Indian', 'LD', 60, 'Paneer|150 g; Potato|2; Cashews|12; Cream|4 tbsp; Tomato|3; Onion|2; Cornflour|2 tbsp', ['rich', 'party']),
  indian('Dal Tadka', 'North Indian', 'LD', 35, 'Toor dal|1 cup; Onion|1; Tomato|1; Garlic|6 cloves; Cumin seeds|1 tsp; Ghee|1 tbsp; Red chilli powder|½ tsp; Turmeric|¼ tsp', ['comfort']),
  indian('Dal Makhani', 'North Indian', 'D', 90, 'Whole urad dal|¾ cup; Rajma|¼ cup; Butter|2 tbsp; Cream|3 tbsp; Tomato|3; Ginger garlic paste|1 tbsp', ['rich', 'soak overnight']),
  indian('Rajma Chawal', 'North Indian', 'L', 60, 'Rajma|1 cup; Rice|1½ cups; Onion|2; Tomato|3; Ginger garlic paste|1 tbsp; Garam masala|1 tsp', ['comfort', 'soak overnight']),
  indian('Chole', 'North Indian', 'LD', 50, 'Kabuli chana|1 cup; Onion|2; Tomato|2; Chole masala|2 tsp; Ginger garlic paste|1 tbsp', ['soak overnight']),
  indian('Kadhi Pakora', 'North Indian', 'L', 50, 'Besan|1 cup; Curd|2 cups; Onion|2; Curry leaves|1 sprig; Fenugreek seeds|½ tsp; Turmeric|½ tsp', ['comfort']),
  indian('Aloo Gobi', 'North Indian', 'LD', 30, 'Potato|3; Cauliflower|1 small; Onion|1; Tomato|1; Turmeric|½ tsp; Coriander leaves|handful'),
  indian('Aloo Matar', 'North Indian', 'LD', 30, 'Potato|3; Peas|1 cup; Onion|1; Tomato|2; Cumin seeds|1 tsp; Garam masala|½ tsp'),
  indian('Bhindi Masala', 'North Indian', 'LD', 30, 'Bhindi|500 g; Onion|2; Amchur|1 tsp; Turmeric|¼ tsp'),
  indian('Baingan Bharta', 'North Indian', 'LD', 40, 'Brinjal|1 large; Onion|2; Tomato|2; Garlic|5 cloves; Green chilli|2; Coriander leaves|handful', ['smoky']),
  indian('Mix Veg', 'North Indian', 'LD', 30, 'Mixed vegetables|3 cups; Onion|1; Tomato|2; Ginger garlic paste|1 tsp; Garam masala|½ tsp', ['everyday']),
  indian('Aloo Paratha', 'North Indian', 'BL', 40, 'Atta|2 cups; Potato|3; Green chilli|2; Coriander leaves|handful; Ghee|to cook; Curd|to serve'),
  indian('Besan Chilla', 'North Indian', 'B', 20, 'Besan|1 cup; Onion|1; Tomato|1; Green chilli|1; Coriander leaves|handful', ['quick', 'high protein']),
  indian('Moong Dal Khichdi', 'North Indian', 'D', 30, 'Moong dal|½ cup; Rice|½ cup; Ghee|1 tbsp; Cumin seeds|1 tsp; Turmeric|¼ tsp', ['light', 'comfort']),
  indian('Jeera Rice', 'North Indian', 'LD', 20, 'Basmati rice|1 cup; Cumin seeds|1 tsp; Ghee|1 tbsp', ['quick', 'side']),
  indian('Veg Pulao', 'North Indian', 'LD', 30, 'Basmati rice|1½ cups; Mixed vegetables|1½ cups; Onion|1; Whole garam masala|1 tbsp; Ghee|1 tbsp'),
  indian('Veg Biryani', 'Mughlai', 'LD', 60, 'Basmati rice|2 cups; Mixed vegetables|2 cups; Curd|½ cup; Onion|3; Biryani masala|2 tsp; Saffron|pinch; Mint leaves|handful; Ghee|2 tbsp', ['weekend']),
  indian('Pav Bhaji', 'Mumbai street food', 'LD', 45, 'Pav|8; Potato|3; Cauliflower|1 cup; Peas|½ cup; Capsicum|1; Tomato|3; Onion|2; Butter|3 tbsp; Pav bhaji masala|2 tbsp; Lemon|1', ['weekend']),
  indian('Poha', 'Maharashtrian', 'B', 20, 'Poha|2 cups; Onion|1; Peanuts|¼ cup; Curry leaves|1 sprig; Mustard seeds|1 tsp; Turmeric|¼ tsp; Lemon|1; Coriander leaves|handful', ['quick']),
  indian('Methi Thepla', 'Gujarati', 'B', 30, 'Atta|2 cups; Methi leaves|1 bunch; Curd|¼ cup; Turmeric|¼ tsp; Red chilli powder|½ tsp', ['travel-friendly']),
  indian('Dhokla', 'Gujarati', 'B', 30, 'Besan|1½ cups; Curd|½ cup; Eno|1 tsp; Mustard seeds|1 tsp; Curry leaves|1 sprig; Green chilli|2', ['light']),
  indian('Masala Dosa', 'South Indian', 'BD', 40, 'Dosa batter|3 cups; Potato|4; Onion|2; Curry leaves|1 sprig; Mustard seeds|1 tsp; Turmeric|¼ tsp'),
  indian('Idli Sambar', 'South Indian', 'B', 30, 'Idli batter|3 cups; Toor dal|½ cup; Sambar masala|1 tbsp; Tamarind|small ball; Mixed vegetables|1 cup; Coconut|½ cup', ['light']),
  indian('Sambar Rice', 'South Indian', 'LD', 45, 'Toor dal|¾ cup; Rice|1 cup; Sambar masala|2 tbsp; Tamarind|small ball; Drumstick|1; Mixed vegetables|1 cup; Curry leaves|1 sprig'),
  indian('Upma', 'South Indian', 'B', 20, 'Rava|1 cup; Onion|1; Curry leaves|1 sprig; Mustard seeds|1 tsp; Green chilli|2; Peas|¼ cup', ['quick']),

  // Ingredients for these come from recipes.js (their videos). The two Bong Eats dishes keep a
  // generic list until their videos are checked (see TODO.md).
  indian('Shahi Paneer', 'North Indian', 'LD', 35, null, ['rich']),
  indian('Dum Aloo', 'Hyderabadi', 'LD', 50, null, ['rich']),
  indian('Methi Malai Matar', 'North Indian', 'LD', 40, null, ['rich']),
  indian('Sarson ka Saag', 'North Indian', 'LD', 150, null, ['winter', 'slow-cooked']),
  indian('Chana Dal Fry', 'North Indian', 'LD', 30, null, ['comfort']),
  indian('Kala Chana Masala', 'North Indian', 'LD', 50, null, ['soak overnight', 'high protein']),
  indian('Lauki Chana Dal', 'North Indian', 'LD', 35, null, ['everyday', 'light']),
  indian('Gobi Paratha', 'North Indian', 'BL', 45, null, ['winter']),
  indian('Paneer Paratha', 'North Indian', 'BL', 40, null, ['high protein']),
  indian('Gatte ki Sabzi', 'Rajasthani', 'LD', 40, null),
  indian('Aloo Posto', 'Bengali', 'L', 30, 'Potato|4; Poppy seeds|4 tbsp, ground; Mustard oil|3 tbsp; Kalonji|½ tsp; Green chilli|3; Turmeric|¼ tsp; Salt|to taste'),
  indian('Cholar Dal', 'Bengali', 'LD', 45, 'Chana dal|1 cup; Coconut|¼ cup, small pieces; Raisins|2 tbsp; Ghee|2 tbsp; Bay leaf|2; Cumin seeds|1 tsp; Dry red chilli|2; Cinnamon|1 inch; Cloves|3; Green cardamom|3; Ginger paste|1 tsp; Turmeric|½ tsp; Sugar|1 tsp; Salt|to taste'),
  indian('Mirchi ka Salan', 'Hyderabadi', 'LD', 45, null, ['tangy']),
  indian('Medu Vada', 'South Indian', 'B', 30, null, ['soak ahead']),
  indian('Lemon Rice', 'South Indian', 'L', 25, null, ['quick', 'tiffin']),
  indian('Bisi Bele Bath', 'South Indian', 'LD', 45, null, ['one-pot']),
  indian('Avial', 'Kerala', 'L', 30, null),
  indian('Vada Pav', 'Mumbai street food', 'LD', 60, null, ['weekend']),
  indian('Misal Pav', 'Maharashtrian', 'BL', 45, null, ['spicy']),
  indian('Paneer Kathi Roll', 'Street food', 'LD', 90, null, ['weekend']),

  // ---- International ----
  world('Margherita Pizza', 'Italian', 'D', 30, 'Pizza base|2; Pizza sauce|½ cup; Mozzarella|200 g; Basil|handful; Olive oil|1 tbsp'),
  world('Penne Arrabbiata', 'Italian', 'LD', 25, 'Pasta|250 g; Tomato|4; Garlic|4 cloves; Chilli flakes|1 tsp; Olive oil|2 tbsp; Parmesan|to serve', ['quick']),
  world('Pesto Pasta', 'Italian', 'LD', 20, 'Pasta|250 g; Basil|2 cups; Pine nuts|2 tbsp; Garlic|2 cloves; Parmesan|½ cup; Olive oil|⅓ cup', ['quick']),
  world('Aglio e Olio', 'Italian', 'D', 15, 'Pasta|250 g; Garlic|8 cloves; Chilli flakes|1 tsp; Olive oil|¼ cup; Parsley|handful', ['quick']),
  world('Mushroom Risotto', 'Italian', 'D', 40, 'Arborio rice|1 cup; Mushroom|200 g; Veg stock|4 cups; Onion|1; Parmesan|½ cup; Butter|2 tbsp'),
  world('Veg Lasagne', 'Italian', 'D', 75, 'Lasagne sheets|9; Mixed vegetables|3 cups; Tomato|5; Mozzarella|200 g; Milk|2 cups; Butter|2 tbsp; Maida|2 tbsp', ['weekend']),
  world('Minestrone Soup', 'Italian', 'D', 40, 'Mixed vegetables|3 cups; Pasta|½ cup; Rajma|½ cup; Tomato|3; Garlic|3 cloves; Veg stock|4 cups', ['light']),
  world('Tomato Basil Soup', 'Continental', 'D', 30, 'Tomato|6; Onion|1; Garlic|3 cloves; Basil|handful; Cream|2 tbsp; Butter|1 tbsp', ['light']),
  world('Mac and Cheese', 'American', 'LD', 30, 'Pasta|250 g; Cheese|200 g; Milk|2 cups; Butter|2 tbsp; Maida|2 tbsp', ['comfort']),
  world('Greek Salad', 'Greek', 'L', 10, 'Cucumber|1; Tomato|2; Onion|1; Capsicum|1; Olives|¼ cup; Feta|100 g; Olive oil|2 tbsp', ['light', 'quick']),
  world('Falafel & Hummus', 'Middle Eastern', 'LD', 45, 'Kabuli chana|2 cups; Tahini|3 tbsp; Garlic|3 cloves; Parsley|handful; Lemon|1; Pita bread|4', ['soak overnight', 'high protein']),
  world('Veg Burrito Bowl', 'Mexican', 'L', 30, 'Rice|1 cup; Rajma|1 cup; Corn|½ cup; Capsicum|1; Tomato|2; Onion|1; Lemon|1; Cheese|to serve'),
  world('Cheese Quesadilla', 'Mexican', 'LD', 15, 'Tortillas|4; Cheese|150 g; Capsicum|1; Corn|½ cup; Onion|1', ['quick']),
  world('Thai Green Curry', 'Thai', 'D', 35, 'Coconut milk|400 ml; Thai green curry paste|3 tbsp; Mixed vegetables|2 cups; Tofu|200 g; Basil|handful'),
  world('Veg Pad Thai', 'Thai', 'D', 25, 'Rice noodles|200 g; Tofu|150 g; Peanuts|¼ cup; Tamarind|1 tbsp paste; Bean sprouts|1 cup; Soy sauce|2 tbsp; Lemon|1'),
  world('Veg Katsu Curry', 'Japanese', 'D', 45, 'Mixed vegetables|2 cups; Bread crumbs|1 cup; Maida|½ cup; Rice|1½ cups; Japanese curry cubes|4; Onion|1; Carrot|1; Potato|1'),
  world('Tofu Stir-fry', 'Chinese', 'D', 20, 'Tofu|200 g; Broccoli|1 head; Capsicum|1; Garlic|3 cloves; Soy sauce|2 tbsp; Cornflour|1 tbsp; Rice|1 cup', ['quick', 'high protein']),
  world('Veg Hakka Noodles', 'Indo-Chinese', 'D', 25, 'Noodles|200 g; Cabbage|1 cup; Carrot|1; Capsicum|1; Spring onion|3; Soy sauce|2 tbsp; Vinegar|1 tsp'),
  world('Veg Fried Rice', 'Indo-Chinese', 'LD', 20, 'Rice|2 cups cooked; Carrot|1; Beans|6; Spring onion|3; Soy sauce|2 tbsp; Garlic|4 cloves', ['quick', 'leftovers']),
  world('Chilli Paneer', 'Indo-Chinese', 'D', 30, 'Paneer|250 g; Capsicum|2; Onion|1; Soy sauce|2 tbsp; Cornflour|3 tbsp; Green chilli|3; Spring onion|2'),
  world('Veg Manchurian', 'Indo-Chinese', 'D', 40, 'Cabbage|2 cups; Carrot|1; Cornflour|4 tbsp; Maida|2 tbsp; Soy sauce|2 tbsp; Garlic|6 cloves; Spring onion|2'),
  world('White Sauce Pasta', 'Italian', 'LD', 25, null, ['quick']),
  world('Bruschetta', 'Italian', 'B', 20, null, ['quick']),
  world('Potato Au Gratin', 'Continental', 'D', 45, null, ['oven']),
  world('Paneer Tikka Tacos', 'Mexican', 'D', 60, null, ['fusion', 'party']),
  world('Thai Red Curry', 'Thai', 'D', 45, null),
  world('Veg Khao Suey', 'Burmese', 'D', 50, null),
  world('Veg Spring Rolls', 'Indo-Chinese', 'D', 60, null, ['party']),
  world('Schezwan Fried Rice', 'Indo-Chinese', 'LD', 40, null, ['spicy']),
  world('Hot and Sour Soup', 'Indo-Chinese', 'D', 30, null, ['light']),
  world('Sweet Corn Soup', 'Indo-Chinese', 'D', 25, null, ['light', 'quick']),
];
