// Ingredients and method for each catalogue dish, taken from its recipe video (see VIDEOS in catalog.js).
// Ingredients follow the video's own list (description, or what's said in the video). The method is a short
// summary in our own words, not the creator's text; the video stays the full reference.
// `from` says where it came from. Dishes missing here keep the catalogue's generic list until they're checked.

export const RECIPES = {
  'Palak Paneer': {
    from: 'description',
    ingredients: 'Spinach|2 bunches; Ginger|1 inch; Garlic|4-6 cloves; Green chilli|2; Ghee|1 tbsp; Oil|1 tbsp; Cumin seeds|¼ tsp; Cloves|3-4; Bay leaf|1; Hing|a pinch; Onion|2-3 small; Tomato|1 medium; Coriander seeds|1 tsp, roasted & crushed; Kasuri methi|½ tbsp; Turmeric|½ tsp; Red chilli powder|1 tsp; Paneer|250-300 g; Cream|1 tbsp + to garnish; Garam masala|a pinch; Salt|to taste',
    method: [
      'Blanch the spinach for 2-3 minutes, then plunge it into ice-cold water.',
      'Blend ginger, garlic and green chilli, add the spinach and blend smooth. Chop a few leaves separately.',
      'Heat ghee and oil; add bay leaf, cloves, cumin and hing.',
      'Add onion and garlic and cook till translucent, then the tomato till soft.',
      'Stir in turmeric, chilli powder, the crushed coriander seeds, kasuri methi and the chopped leaves.',
      'Add the spinach purée and ½ cup hot water; season with salt.',
      'Add the paneer and a pinch of garam masala, simmer a minute, and finish with cream and ginger juliennes.',
    ],
  },
  'Paneer Butter Masala': {
    from: 'description',
    ingredients: 'Paneer|200 g; Ghee|3 tbsp; Butter|6 tbsp + 3 small cubes; Bay leaf|1; Green cardamom|2; Cloves|3; Ginger|1 inch; Garlic|3 cloves; Green chilli|1; Onion|3 medium; Dry red chilli (Kashmiri)|2; Cashews|18; Tomato|7 medium; Degi red chilli powder|about 2 tsp; Coriander powder|1 tsp; Turmeric|¼ tsp; Curd|3 tbsp + to garnish; Kewra water|2-3 drops; Honey|1-2 tbsp; Kasuri methi|1 tbsp; Coriander leaves|to garnish; Salt|to taste',
    method: [
      'Soak the paneer cubes in warm salted water.',
      'Mix 1 tsp chilli powder with the coriander powder, turmeric, curd and butter.',
      'Heat ghee; cook bay leaf, cardamom, cloves, ginger, garlic, green chilli and 2 sliced onions till translucent.',
      'Add the curd mix and dry chillies for 2-3 minutes, then the cashews, 6 tomatoes, salt and a little chilli powder.',
      'Add 1½ cups water, cover and cook 10-12 minutes. Add the kewra water, cool, and blend smooth.',
      'In 4 tbsp butter, cook 1 chopped onion, a pinch of chilli powder and 1 chopped tomato till soft.',
      'Add the blended gravy, 2 tbsp butter, the honey and kasuri methi; bring to a boil.',
      'Add the drained paneer and simmer 4-5 minutes. Garnish with curd and coriander.',
    ],
  },
  'Matar Paneer': {
    from: 'transcript',
    ingredients: 'Paneer|400 g; Peas|500 g; Tomato|3-4; Green chilli|2; Ginger|1 inch; Cumin seeds|½ tsp; Hing|a pinch; Cream|3 tbsp malai, whisked; Turmeric|½ tsp; Coriander powder|1 tsp; Red chilli powder|under ¼ tsp; Garam masala|under ¼ tsp; Coriander leaves|1 tbsp; Oil|3 tbsp; Salt|¾ tsp',
    method: [
      'Grind the tomatoes, green chillies and ginger to a paste.',
      'Fry the peas in ½ tbsp oil, covered for 2 minutes, till tender; set aside.',
      'Fry the paneer pieces in ½ tbsp oil till lightly browned on both sides.',
      'In 2 tbsp oil, add cumin, hing, turmeric, coriander and chilli powders and the tomato paste; stir till the oil floats on top.',
      'Add the whisked malai and cook again till the oil separates.',
      'Add 1-1½ cups water; once it boils, add salt, the peas and paneer, cover and cook 2 minutes.',
      'Finish with garam masala and coriander. Serves 4-5.',
    ],
  },
  'Kadai Paneer': {
    from: 'description',
    ingredients: 'Coriander seeds|1½ tbsp; Cumin seeds|1 tbsp; Dry red chilli (Kashmiri)|4-5; Black peppercorns|1½ tbsp; Oil|1 tbsp + 1 tsp; Ghee|1 tsp; Ginger|1 inch; Onion|3; Ginger garlic paste|1 tsp; Turmeric|½ tsp; Degi red chilli powder|1 tsp; Coriander powder|1 tsp; Tomato|3; Capsicum|½; Paneer|250 g; Kashmiri red chilli powder|1 tsp; Cream|1 tbsp (optional); Coriander leaves|a sprig; Salt|to taste',
    method: [
      'Kadai masala: dry-roast 1½ tbsp coriander seeds, 2 tsp cumin, the Kashmiri chillies and peppercorns with a little salt; cool and grind.',
      'Heat oil, add 1 tsp cumin and the ginger, then 2 chopped onions and the ginger-garlic paste; cook till the raw smell goes.',
      'Add turmeric, chilli and coriander powders, then 2 puréed tomatoes, salt and a splash of water; cook down.',
      'In another pan with ghee and oil, sauté 1 sliced onion, the capsicum and 1 sliced tomato for a minute; add the paneer.',
      'Add Kashmiri chilli powder and 1 tbsp kadai masala, pour in the gravy and mix.',
      'Stir in the cream and garnish with coriander.',
    ],
  },
  'Paneer Bhurji': {
    from: 'description + transcript',
    ingredients: 'Paneer|300 g, grated; Onion|1 cup chopped; Tomato|1 cup chopped; Ginger|1 tsp grated; Garlic|1 tbsp grated; Green chilli|1 tbsp chopped + 3; Turmeric|½ tsp; Kashmiri red chilli powder|1½ tsp; Coriander powder|1 tsp; Cumin powder|½ tsp; Pav bhaji masala|1 tbsp; Garam masala|1 tsp; Besan|2 tbsp, roasted; Kasuri methi|1 tsp; Butter|3 tbsp; Oil|4 tbsp; Coriander leaves|a big handful; Salt|about 1½ tsp',
    method: [
      'On a big tawa or pan, heat 2 tbsp butter with 4 tbsp oil; fry the onion for 3-4 minutes on medium.',
      'Add the grated garlic and ginger, then the green chillies.',
      'Add as much tomato as onion and cook till it all melts down.',
      'Add turmeric, Kashmiri chilli, coriander and cumin powders, pav bhaji masala and garam masala; roast well, with a splash of water if it sticks.',
      'Stir in the roasted besan and a little coriander, then about 1½ cups water and the salt; bring to a boil.',
      'Mix in the grated paneer on medium heat, add plenty of coriander, and finish with butter and roasted kasuri methi. Serve with buttered pav or kulcha.',
    ],
  },
  'Malai Kofta': {
    from: 'description',
    ingredients: 'Potato|1 medium, boiled; Paneer|150 g; Mawa|50 g; Black pepper|½ tsp; Ginger|1½ inch; Baking soda|a pinch; Cornflour|1 tbsp; Oil|for deep frying + 2 tbsp; Dry fruits|¼ cup, chopped; Coriander leaves|½ tbsp; Cardamom powder|½ tsp; Ghee|3 tbsp; Bay leaf|2; Green cardamom|3-4; Black peppercorns|6-8; Cumin seeds|½ tbsp; Onion|2 medium; Coriander powder|1 tbsp; Red chilli powder|1 tbsp + 1 tsp; Turmeric|½ tsp; Garlic|3-4 cloves; Tomato|2 medium; Cashews|½ cup; Kasuri methi|a pinch; Cream|to garnish; Salt|to taste',
    method: [
      'Grate the potato, paneer and mawa; mix with salt, pepper, baking soda, ½ inch grated ginger and the cornflour.',
      'For the filling, mix the dry fruits with cardamom powder, coriander and a little of the kofta mixture.',
      'Stuff each ball with filling, shape lemon-sized koftas and deep-fry on low heat till golden.',
      'Gravy: heat 2 tbsp ghee with the oil; add bay leaf, peppercorns, cardamom and cumin, then the onion till translucent.',
      'Add coriander, chilli and turmeric powders with ginger and garlic, then the tomatoes and cashews; cook till soft.',
      'Cool, blend fine and strain.',
      'Heat 1 tbsp ghee, add 1 tsp chilli powder, kasuri methi and the purée; cook till the raw smell goes.',
      'Pour the gravy over the koftas and finish with cream. Serve with roti.',
    ],
  },
  'Dal Tadka': {
    from: 'description',
    ingredients: 'Toor dal|½ cup, soaked; Moong dal|3 tbsp, soaked; Ghee|5 tbsp; Oil|3 tbsp; Ginger|2 inch; Garlic|½ tbsp chopped + 3-4 cloves; Green chilli|1; Onion|1 medium; Cumin seeds|½ tsp; Turmeric|½ tsp; Red chilli powder|2 tsp; Dry red chilli (Kashmiri)|2-3; Kashmiri red chilli powder|½ tsp; Hing|a pinch; Coriander leaves|to garnish; Salt|to taste',
    method: [
      'Roast both dals in 2 tbsp ghee in a pressure cooker for 2-3 minutes.',
      'Add sliced ginger, green chilli, salt, turmeric, chilli powder and 1½ cups water; cook for 3 whistles.',
      'First tadka: in 1 tbsp ghee and oil, fry cumin, chopped ginger and garlic, then the onion till translucent; add chilli powder, turmeric and salt for 2-3 minutes.',
      'Add the cooked dal and simmer 3-4 minutes.',
      'Second tadka: heat 2 tbsp ghee and oil, add sliced garlic, dry chillies, hing and Kashmiri chilli powder till they sizzle.',
      'Pour the tadka over the dal and garnish with coriander.',
    ],
  },
  'Dal Makhani': {
    from: 'description',
    ingredients: 'Whole urad dal|3 cups, soaked overnight; Rajma|½ cup, soaked overnight; Chana dal|¼ cup, soaked; Ghee|3 tbsp; Butter|4 tbsp, unsalted; Garlic|5-6 cloves + 1 tbsp garlic juice; Ginger|1 inch; Green chilli|1; Oil|1½ tsp; Degi red chilli powder|2½ tsp; Turmeric|¼ tsp; Coriander powder|1 tsp; Cumin seeds|½ tsp; Black peppercorns|10-12; Kasuri methi|1½ tsp; Hing|a pinch; Tomato|½ cup purée; Cream|to garnish; Coriander leaves|a sprig; Salt|to taste',
    method: [
      'Pressure-cook the soaked dals in 1½ tbsp ghee with water, the garlic juice, chilli powder, turmeric, coriander powder, salt and 2 tbsp butter for 4-5 whistles (about 80% done).',
      'Grind the garlic, ginger, green chilli, salt and a little oil to a paste.',
      'Dry-roast cumin, peppercorns and 1 tsp kasuri methi with salt; grind to a powder.',
      'In a heavy pot, heat 1½ tbsp ghee; sauté the paste, then the chilli powder and hing.',
      'Add the tomato purée and salt; cook 4-5 minutes.',
      'Add the dal, cover and cook 5-10 minutes, mashing some of it.',
      'Finish with 2 tbsp butter, 1 tsp of the roasted masala and crushed kasuri methi. Garnish with cream and coriander; serve with rice.',
    ],
  },
  'Rajma Chawal': {
    from: 'description + transcript',
    ingredients: 'Rajma|1¼ cups (chitra); Oil|⅓ cup; Bay leaf|1; Black cardamom|1; Cumin seeds|2 tsp; Onion|1 cup, grated; Green chilli|1; Ginger paste|1 tbsp; Garlic paste|1 tbsp; Kashmiri red chilli powder|1 tbsp; Turmeric|½ tsp; Coriander powder|1 tbsp; Tomato|2 cups, grated; Kasuri methi|½ tsp, powdered; Garam masala|¼ tsp; Ghee|1 spoon, to serve; Salt|to taste; Rice|to serve',
    method: [
      'Soak the rajma overnight; it swells to about three times its size.',
      'In a pressure cooker, heat oil with the bay leaf, a lightly crushed black cardamom and cumin; add the onion and green chilli and cook till browned, then the ginger and garlic pastes till they lose their raw smell.',
      'Add turmeric, Kashmiri chilli and coriander powder and roast well, then the grated tomato; cook till thick.',
      'Add the soaked rajma (without the soaking water) and cook 5-7 minutes; add water once the masala starts to stick.',
      'Pressure-cook: one whistle on high, then low heat till the beans are soft.',
      'Stir in kasuri methi, garam masala and coriander and simmer 5-10 minutes, mashing a few beans for a creamier gravy.',
      'Serve over rice with a spoon of ghee.',
    ],
  },
  'Chole': {
    from: 'description + transcript',
    ingredients: 'Kabuli chana|2 cups (small); Dried amla|3-4 slices; Tea leaves|1½ tbsp; Baking soda|1½ tsp; Chole masala|3 tbsp (the video makes it from whole spices); Oil|½ cup; Hing|½ tsp; Garlic|2 tsp, chopped; Ginger|1 tbsp, chopped; Green chilli|2; Onion|½ cup, chopped; Turmeric|½ tsp; Kashmiri red chilli powder|1¾ tsp; Tomato|¾ cup, puréed; Tamarind|2 tbsp tamarind water; Black salt|to taste; Ghee|1 tbsp; Salt|to taste; Potato|boiled, to garnish; Onion rings|to garnish',
    method: [
      'Soak the chickpeas overnight.',
      'Boil water with the dried amla and tea leaves for about 5 minutes; strain it over the chickpeas in a pressure cooker, put the amla back in, and add salt and baking soda.',
      'Pressure-cook: one quick whistle, then 6-7 on low till very soft. Keep the dark cooking water.',
      'Chole masala: dry-roast dry red chillies, bay leaf, coriander seeds, cumin, peppercorns, cloves, cardamom, mace, cinnamon, nutmeg and black cardamom on low till slightly dark; add ajwain, kasuri methi and anardana for a moment, cool, and grind with amchur.',
      'In an iron kadai if you have one, heat oil; add hing, garlic, ginger and green chillies, then the onion till brown.',
      'Add turmeric, Kashmiri chilli and plenty of chole masala; roast briefly on low with a splash of water so it doesn’t burn.',
      'Add the tomato purée and cook till the oil separates.',
      'Add the chole with some of their water, black salt and salt; cook 5-10 minutes till thick and dark. Balance with tamarind water, and top with ghee heated with Kashmiri chilli.',
    ],
  },
  'Kadhi Pakora': {
    from: 'description',
    ingredients: 'Besan|1 cup (125 g); Curd|2 cups; Oil|2 tbsp + for frying; Cumin seeds|¾ tsp; Ginger|1 tsp, grated; Fenugreek seeds|¼ tsp; Green chilli|4; Turmeric|½ tsp; Coarse red chilli powder|½ tsp; Dry red chilli|2; Hing|½ pinch; Curry leaves|10-12; Kashmiri red chilli powder|¼ tsp; Salt|a little under 2 tsp',
    method: [
      'Whisk ½ cup besan with water to a smooth, medium-thick pakora batter; rest it 20 minutes.',
      'Blend the other ½ cup besan with the curd for the kadhi.',
      'Beat the pakora batter 4-5 minutes, drop small spoonfuls into medium-hot oil and fry till golden.',
      'In 1 tbsp oil, lightly fry cumin, ginger, fenugreek seeds and whole green chillies (don’t let them darken).',
      'Add the curd mixture and about 4½ cups water; stir constantly till it boils, adding the turmeric and coarse chilli.',
      'Once it boils, add the salt and pakoras; simmer 10-12 minutes on low-medium, stirring now and then.',
      'Tadka: heat 1 tbsp oil with cumin, hing, dry chillies and curry leaves; off the heat add Kashmiri chilli powder and pour over.',
    ],
  },
  'Aloo Gobi': {
    from: 'description',
    ingredients: 'Potato|3 (300 g); Cauliflower|300 g; Tomato|2; Ginger|½ inch + a little for juliennes; Green chilli|2; Oil|2-3 tbsp; Coriander leaves|2-3 tbsp; Cumin seeds|1 tsp; Hing|½ pinch; Turmeric|½ tsp; Coriander powder|1 tsp; Red chilli powder|a little; Bay leaf|1-2; Cinnamon|1 small stick; Cloves|2-3; Black peppercorns|a few; Garam masala|a pinch; Salt|to taste',
    method: [
      'Cut the potatoes and cauliflower into pieces (keep the potatoes in water till needed).',
      'Roast cumin in a little oil, add the vegetables with salt and turmeric; stir-fry 2 minutes, then cover and cook on low about 20 minutes, stirring every 5.',
      'Meanwhile, grind the tomatoes, green chillies and ginger to a paste.',
      'Masala: heat 2 tbsp oil; fry cumin, hing, bay leaf, cinnamon, cloves and peppercorns.',
      'Add the tomato paste, chilli and coriander powders; cook till the oil separates.',
      'Add a little water, salt, ginger juliennes, garam masala and coriander; bring to a boil.',
      'Mix the masala into the vegetables and cook 4-5 minutes.',
    ],
  },
  'Aloo Matar': {
    from: 'transcript',
    ingredients: 'Potato|4, boiled; Peas|1 cup; Tomato|2; Green chilli|2; Ginger|1 inch; Oil|2 tbsp; Cumin seeds|½ tsp; Hing|a pinch; Turmeric|½ tsp; Coriander powder|1 tsp; Red chilli powder|¼ tsp; Garam masala|¼ tsp; Coriander leaves|1 tbsp + to garnish; Ghee|1 tsp (optional); Salt|a little over 1 tsp',
    method: [
      'Grind the tomatoes, green chillies and ginger to a paste.',
      'Heat oil; add cumin and hing, lower the heat, then turmeric, coriander powder, the paste and chilli powder; cook till the oil separates.',
      'Add the peas, cover and simmer on low for 2-3 minutes till soft.',
      'Crumble in the peeled boiled potatoes and stir on higher heat for a minute (for a dry sabzi, season and stop here).',
      'Add about 1 cup water, salt, garam masala and coriander; cover and simmer 3-4 minutes.',
      'Stir in a teaspoon of ghee if you like. Serves 3-4.',
    ],
  },
  'Baingan Bharta': {
    from: 'transcript',
    ingredients: 'Brinjal|4 long; Onion|4, roughly chopped (as many as brinjals); Garlic|8-10 cloves; Mustard oil|generous (or half refined oil); Green chilli|2-3; Coriander leaves|stalks + leaves; Cumin seeds|1 tsp; Tomato|2; Coriander powder|½ tsp (optional); Degi red chilli powder|1 tsp; Salt|to taste',
    method: [
      'Cut 4-5 deep slits in each brinjal, push garlic cloves into them and rub with a little mustard oil.',
      'Roast over a flame (or in an oven or air fryer), high at first then lower, turning so the thick base cooks too, till charred and soft.',
      'Let it cool a little, peel, and chop roughly across the fibres while still warm, with the roasted garlic; keep the smoky juices.',
      'Temper cumin in mustard oil, add the roughly chopped onions and cook only till translucent, not brown.',
      'Add green chillies and chopped coriander stalks, then the tomatoes, coriander powder and degi chilli; cook till the tomatoes soften, then 2 minutes more.',
      'Add the brinjal and salt and cook on low till the oil starts to show. Finish with coriander leaves.',
    ],
  },
  'Mix Veg': {
    from: 'transcript',
    ingredients: 'Mixed vegetables|1 kg (carrot, broccoli, cauliflower, peas, beans, cabbage, capsicum); Tomato|1-2; Paneer|a few cubes; Cumin seeds|½ tsp; Hing|1-2 pinches; Turmeric|½ tsp; Coriander powder|1 tsp; Red chilli powder|¼ tsp; Ginger|1 inch, grated; Green chilli|2; Coriander leaves|2-3 tbsp; Oil|2 tbsp; Salt|1 tsp',
    method: [
      'Dice all the vegetables.',
      'Heat oil, add cumin and hing, then turmeric, ginger, green chilli and coriander powder; sauté briefly.',
      'Add the vegetables with salt and chilli powder and toss to coat.',
      'Add a splash of water, cover and cook 4 minutes; stir and cook 2 minutes more, keeping them crunchy.',
      'Add the chopped tomato and cover for 1-1½ minutes.',
      'Stir in the paneer (fresh, or lightly fried) for 1-2 minutes and finish with coriander.',
    ],
  },
  'Aloo Paratha': {
    from: 'description + transcript',
    ingredients: 'Atta|3 cups; Ghee|1 tbsp + to cook; Potato|5-6, boiled; Coriander powder|2 tbsp; Red chilli powder|1 tsp; Roasted cumin powder|1 tsp; Amchur|1 tsp; Ajwain|½ tsp; Salt|1 tbsp; Coriander leaves|a handful; Ginger|1 inch; Green chilli|5-6; Onion|2; Pizza seasoning|½ tsp (optional)',
    method: [
      'Mix the atta with water only (no salt or ghee yet) into a rough dough; press dents into it, add a little water to the dents and leave it uncovered for 5 minutes.',
      'Mash the boiled potatoes completely smooth, then mix in the coriander powder, chilli powder, cumin powder, amchur, ajwain, salt, coriander leaves, ginger, green chilli, onion (and pizza seasoning if using).',
      'Knead the rested dough smooth with 1 tbsp ghee; cover for 5 minutes.',
      'Roll a ball into a small round, then roll out the four sides so it’s roughly square; put filling in the centre, fold the corners over to seal and press gently to spread the filling.',
      'Roll gently from the sealed side into a square paratha, not too thin.',
      'Cook on a hot tawa, first dry on both sides, then with ghee or oil on medium-high till crisp and puffed.',
    ],
  },
  'Besan Chilla': {
    from: 'description + transcript',
    ingredients: 'Besan|1½ cups (150 g); Spinach|½ cup, finely chopped; Cabbage|½ cup, grated; Tomato|1; Oil|2 tbsp; Coriander leaves|1 tbsp; Green chilli|2; Ginger|½ inch, grated; Salt|1 tsp',
    method: [
      'Whisk the besan with a little water at a time till smooth, then thin it to a pouring batter (about 1 cup water in all).',
      'Stir in the spinach, cabbage, tomato, coriander, green chillies, ginger and salt.',
      'Grease a non-stick tawa and let it cool slightly, then spread 2-3 tbsp batter thinly on low heat.',
      'Drizzle oil around and over, cook on medium till golden underneath, then flip and cook the other side.',
      'Makes about 7. Serve with green chutney or ketchup.',
    ],
  },
  'Moong Dal Khichdi': {
    from: 'transcript',
    ingredients: 'Moong dal|½ cup, soaked; Basmati rice|½ cup, soaked; Peas|½ cup; Ghee|2-3 tbsp; Ginger|½ inch, grated; Cumin seeds|½ tsp; Turmeric|¼ tsp; Hing|1-2 pinches; Salt|1 tsp',
    method: [
      'Pressure-cook the dal, rice and peas with 4½ cups water, the salt and turmeric for one whistle; let the pressure drop on its own.',
      'Heat ghee, add hing, cumin and ginger, and pour this tadka over the khichdi.',
      'Mix, top with a little more ghee, and serve with curd, papad or pickle.',
    ],
  },
  'Jeera Rice': {
    from: 'description',
    ingredients: 'Rice|1 glass; Cumin seeds|1 tbsp; Ghee|2 tbsp; Onion|1 (optional); Green chilli|2 (optional); Salt|to taste',
    method: [],
  },
  'Veg Pulao': {
    from: 'description + transcript',
    ingredients: 'Basmati rice|1 glass (about 250 g); Onion|2 medium; Green chilli|2; Cashews|12-15; Cumin seeds|1 tsp; Mixed vegetables|cauliflower, carrot, peas, beans; Potato|2; Bay leaf|2; Dry red chilli|2; Cinnamon|2 inch; Black cardamom|1; Cloves|4; Black peppercorns|6-8; Mace|a little; Nutmeg|a pinch; Ginger garlic paste|1 tsp; Ghee|3 tbsp (or oil); Salt|1¼ tsp',
    method: [
      'Soak the rice while you prep.',
      'In a pressure cooker, fry the cashews in ghee till light brown; set aside.',
      'Add cumin, bay leaves, dry red chillies and the whole spices, then the green chillies and onion; cook on medium till golden.',
      'Add the ginger-garlic paste briefly, then the vegetables; cover (without the whistle) and cook 2-3 minutes, stirring now and then.',
      'Add the drained rice and cashews and toss gently for half a minute.',
      'Add 1½ times as much water as rice, and the salt; cook for one whistle on high, then turn off and let the pressure drop on its own.',
      'Fluff gently and rest uncovered for 2-3 minutes.',
    ],
  },
  'Veg Biryani': {
    from: 'description',
    ingredients: 'Basmati rice|300 g; Carrot|100 g; Cauliflower|100 g; Potato|100 g; Paneer|50 g; Curd|200 g; Fried onions|40 g; Mint leaves|40 g; Coriander leaves|a handful; Green chilli|3; Ginger garlic paste|1 tbsp; Shahi jeera|1 tsp; Whole garam masala|1 tsp; Biryani masala|1 packet; Almonds|15 g; Cashews|15 g; Oil|100 ml; Salt|to taste',
    method: [
      'Soak the rice for an hour.',
      'Heat oil; fry the whole garam masala and shahi jeera, then the ginger-garlic paste.',
      'Add the vegetables, cut into batons, with salt; cook till half done.',
      'Stir in mint, coriander, green chillies, biryani masala, half the curd and the paneer.',
      'Boil the rice till about 70% cooked and drain.',
      'Layer half the vegetables, some curd, nuts and fried onions, then half the rice; repeat.',
      'Top with fried onions, cover tightly and cook on the lowest heat for about 5 minutes.',
    ],
  },
  'Pav Bhaji': {
    from: 'description',
    ingredients: 'Pav bhaji masala|2 tbsp + 1 tsp (the video makes it from whole spices); Dry red chilli (Kashmiri)|15-20, soaked; Garlic|¾ cup cloves; Cauliflower|1 medium; Peas|¾ cup; Butter|100 g + to serve; Oil|2 tbsp; Cumin seeds|2 tsp + a pinch; Onion|2-3 medium; Capsicum|2 medium; Potato|7-8 medium, boiled; Tomato|7-8 medium; Beetroot|1 medium, boiled; Coriander leaves|2 handfuls; Kashmiri red chilli powder|1 tsp; Coriander powder|1 tbsp; Turmeric|½ tsp + a pinch; Kasuri methi|1 tsp; Green chilli|2; Garam masala|a pinch; Lemon|1 tsp juice + to serve; Pav|to serve; Salt|to taste',
    method: [
      'Masala (or use ready pav bhaji masala): dry-roast coriander seeds, cumin, cloves, star anise, black cardamom, cinnamon, bay leaves, Kashmiri chillies, fennel and kasuri methi; cool and grind with turmeric, dry ginger, hing, black salt, amchur and salt.',
      'Grind the soaked chillies to a runny paste, and the garlic with water to a thin paste.',
      'Boil the cauliflower and peas with a pinch of turmeric and salt till soft; drain.',
      'On a big tawa, heat butter and oil, crackle cumin, and cook the onions till pinkish; add the capsicum on high for 2-3 minutes.',
      'Add the potatoes, tomatoes, boiled vegetables, beetroot, salt, masala, spice powders and green chilli paste; break everything down.',
      'Add the garlic and chilli pastes and 1-2 cups hot water; mash well on low heat, thinning with hot water to taste.',
      'Finish with a butter tadka (cumin, chilli paste, garlic water, a little masala, garam masala), coriander and lemon. Serve with buttered pav.',
    ],
  },
  'Poha': {
    from: 'description + transcript',
    ingredients: 'Poha|2 cups (100 g); Peanuts|½ cup (50 g); Onion|2 medium; Green chilli|2-3; Lemon|2 tbsp juice; Curry leaves|15-17; Cumin seeds|½ tsp; Mustard seeds|½ tsp; Sugar|½ tsp (optional); Turmeric|⅓ tsp; Oil|3-4 tbsp; Coriander leaves|a handful; Sev|to garnish; Salt|to taste',
    method: [
      'Rinse the poha under running water in a strainer and leave it to soften for 10-15 minutes.',
      'Dry-roast the peanuts for 2-3 minutes on low-medium heat; set aside.',
      'Heat oil, crackle cumin and mustard seeds, add green chillies and curry leaves, then the sugar and onion; cook till golden.',
      'Add turmeric for a few seconds, then the peanuts and poha; mix gently, add salt, cover and cook 1 minute on low.',
      'Add lemon juice and coriander and cover for another minute.',
      'Serve with sev and a lemon wedge.',
    ],
  },
  'Methi Thepla': {
    from: 'transcript',
    ingredients: 'Atta|4 cups; Methi leaves|1 cup (250 g), finely chopped; Curd|½ cup; Oil|3 tsp + for cooking; Turmeric|¼ tsp; Cumin seeds|¼ tsp; Ajwain|¼ tsp; Red chilli powder|¼ tsp; Green chilli|2; Salt|1 tsp',
    method: [
      'Mix the atta with methi, curd, 3 tsp oil, the spices, salt and green chilli, then knead to a dough with a little water; rest 20 minutes.',
      'Roll small portions thin, about 7-8 inches across, dusting with flour.',
      'Cook on a hot oiled tawa, turning when brown spots appear; brush both sides with oil and press so it cooks evenly.',
      'Spinach or bathua can stand in for methi. Serve with pickle, curd or chutney.',
    ],
  },
  'Dhokla': {
    from: 'description + transcript',
    ingredients: 'Besan|1½ cups (180 g); Tartaric acid|1 tsp; Sugar|4 tbsp; Oil|2½ tbsp; Baking soda|¾ tsp; Mustard seeds|½ tsp; Curry leaves|10-12; Green chilli|3; Lemon|1 tbsp juice; Coriander leaves|to garnish; Coconut|grated, to garnish; Salt|¾ tsp',
    method: [
      'Sift the besan.',
      'Dissolve ½ tsp salt, the tartaric acid and 2 tbsp sugar in about 1 cup + 2 tbsp water, add 1½ tbsp oil, then whisk in the besan to a smooth pouring batter; beat 2-3 minutes and rest 10 minutes.',
      'Grease a 7-inch tin, and bring about a litre of water to a boil in a wide covered pan with a stand inside.',
      'Just before steaming, sieve the baking soda over the batter with a spoon of water and mix; it will froth up. Pour into the tin.',
      'Steam, covered, on medium-high for about 25 minutes; cool 15 minutes, then turn out and cut.',
      'Tadka: crackle mustard seeds in 1 tbsp oil, add curry leaves and slit chillies, then 1 cup water, 2 tbsp sugar and ¼ tsp salt; boil till the sugar dissolves, turn off and add the lemon juice.',
      'Spoon the tadka over the dhokla and top with coriander and coconut.',
    ],
  },
  'Upma': {
    from: 'description',
    ingredients: 'Rava|150 g; Green chilli|1; Ginger|1 inch, grated; Lemon|1 tbsp juice; Onion|1 large; Tomato|1 large; Cashews|10-12; Curry leaves|a sprig; Urad dal|1 tsp; Chana dal|1 tsp; Cumin seeds|⅓ tsp; Mustard seeds|⅓ tsp; Red chilli powder|¼ tsp; Sugar|½ tsp; Oil|3 tbsp; Salt|to taste',
    method: [],
  },
  'Penne Arrabbiata': {
    from: 'description',
    ingredients: 'Pasta|200 g (the video makes fresh fettuccine from 200 g maida); Olive oil|2 tbsp; Garlic|2 tbsp, chopped; Basil|a handful; Chilli flakes|1 tbsp; Oregano|1 tbsp; Kashmiri red chilli powder|1 tsp; Tomato|5-6 medium, puréed; Tomato purée|200 g, canned; Sugar|to taste; Parmesan|to serve; Salt|to taste',
    method: [
      'Optional fresh pasta: knead 200 g maida, ¼ tsp salt and about 100 ml water into a smooth dough, rest it, roll thin, layer, fold and cut into strips.',
      'Heat olive oil and cook the garlic on medium; add a few torn basil leaves, then the chilli flakes, oregano and Kashmiri chilli powder on low for a few minutes.',
      'Add both tomato purées, salt and a little sugar; cover and cook 20-25 minutes, stirring now and then.',
      'Tear in more basil at the end.',
      'Boil the pasta in salted water, then toss it in the sauce, loosening with pasta water if it dries.',
      'Serve with parmesan.',
    ],
  },
  'Pesto Pasta': {
    from: 'description',
    ingredients: 'Pasta|250 g penne; Basil|100 g; Parmesan|50 g + to serve; Walnuts|4-5; Garlic|1 clove; Olive oil|5-6 tbsp; Salt|to taste',
    method: [
      'In a chopper, blend 2-3 tbsp olive oil with the garlic, walnuts and a pinch of salt.',
      'Add the basil, parmesan and 3 tbsp olive oil; blend to a coarse paste, scraping down the sides.',
      'Boil the pasta in well-salted water for about 8 minutes; keep some pasta water.',
      'Toss the hot pasta with pesto and parmesan, loosen with 1-2 tbsp hot pasta water, and adjust the salt.',
    ],
  },
  'Aglio e Olio': {
    from: 'description',
    ingredients: 'Pasta|200 g spaghetti; Garlic|4 cloves; Parsley|a handful; Olive oil|2-3 tbsp, extra virgin; Chilli flakes|1½ tsp; Salt|to taste',
    method: [
      'Boil the spaghetti whole in well-salted water.',
      'Meanwhile, slice the garlic thinly and chop the parsley.',
      'Warm the olive oil, turn the heat low and cook the garlic gently till soft; add the chilli flakes.',
      'When the garlic is just golden, add 2 ladles of pasta water and stir hard so it turns into a light sauce.',
      'Move the pasta straight into the pan with the parsley and salt; toss till glossy, adding pasta water if needed.',
    ],
  },
  'Veg Lasagne': {
    from: 'description',
    ingredients: 'Lasagne sheets|homemade from 200 g maida, or bought; Olive oil|4 tbsp; Onion|1 medium; Garlic|2 tbsp, chopped; Kashmiri red chilli powder|1 tsp; Tomato|2 cups fresh purée; Tomato purée|200 g, bought; Chilli flakes|1 tbsp + 1 tsp; Oregano|2 tsp; Sugar|2 pinches; Black pepper|2 pinches; Basil|10-12 leaves; Butter|30 g; Maida|30 g (+200 g for sheets); Milk|400 ml; Nutmeg|a pinch; Carrot|⅓ cup; Zucchini|⅓ cup; Mushroom|⅓ cup; Capsicum|¾ cup, mixed colours; Corn|¼ cup; Broccoli|¼ cup, blanched; Mozzarella|for layering; Parmesan|for layering; Salt|to taste',
    method: [
      'Red sauce: soften the onion and garlic in olive oil, add Kashmiri chilli, both tomato purées, salt, chilli flakes, oregano, sugar and pepper; cover and simmer 10-12 minutes, then tear in the basil.',
      'White sauce: melt the butter, cook the maida on low for 2-3 minutes, whisk in the milk in three goes until smooth and thick; season with salt and nutmeg.',
      'Vegetables: sauté garlic in olive oil, add the carrot and zucchini, then the rest with oregano, chilli flakes, a pinch of sugar, salt and pepper for 1-2 minutes.',
      'Sheets (optional): knead 200 g maida, ¼ tsp salt and about 100 ml water, rest, roll thin and cut into rectangles.',
      'Layer: a thin coat of red sauce, sheets, red sauce, vegetables, white sauce, mozzarella and parmesan; repeat 4-5 times.',
      'Bake at 180°C for 30-35 minutes (the video uses a covered pot on a bed of salt on the stove, 30-45 minutes).',
    ],
  },
  'Minestrone Soup': {
    from: 'description',
    ingredients: 'Olive oil|1 tbsp; Capsicum|½; Celery|½ tbsp, finely chopped; Basil|a few leaves; Zucchini|diced; Tomato purée|as needed; Tomato ketchup|2 tbsp; Tabasco|1 tbsp; Veg stock|as needed; Mixed vegetables|1 cup; Pasta|a handful, boiled; Cornflour|½ tsp; Oregano|1 tsp; Black pepper|crushed, to serve; Salt|to taste',
    method: [
      'Sauté the capsicum, celery, basil and zucchini in olive oil for a few minutes.',
      'Add the tomato purée and cook 3-4 minutes, then the ketchup and Tabasco.',
      'Pour in the stock and bring to a boil; add salt and the vegetables and simmer till tender.',
      'Add the boiled pasta, and thicken with the cornflour mixed in a spoon of water.',
      'Finish with oregano, crushed pepper and basil.',
    ],
  },
  'Tomato Basil Soup': {
    from: 'description',
    ingredients: 'Tomato|5-6 medium; Olive oil|1 tbsp; Garlic|1 tbsp, chopped; Black pepper|¼ tsp; Oregano|½ tsp; Chilli flakes|1 tsp; Sugar|1 tsp; Basil|2-3 leaves; Cornflour|1 tbsp; Cream|1 tbsp; Salt|to taste',
    method: [
      'Score the tomatoes, blanch 2-3 minutes, cool in iced water, peel and blend smooth.',
      'Sauté the garlic in olive oil, then strain the purée into the pan.',
      'Add salt, pepper, oregano and chilli flakes, then the sugar; cook 5-6 minutes.',
      'Add about 250 ml hot water and the basil; thicken with the cornflour mixed in 50 ml water.',
      'Stir in the cream and serve with croutons.',
    ],
  },
  'Falafel & Hummus': {
    from: 'description',
    ingredients: 'Kabuli chana|2 cups, soaked 7-8 hours; Tahini|⅓ cup (the video makes it from toasted sesame and olive oil); Garlic|9-10 cloves; Lemon|1 tbsp juice; Olive oil|3-4 tbsp; Onion|½ cup; Green chilli|2-3; Parsley|1 cup, packed; Coriander leaves|½ cup, packed; Mint leaves|a few sprigs; Spring onion|⅓ cup greens; Cumin powder|1 tbsp; Coriander powder|1 tbsp; Red chilli powder|1 tbsp; Black pepper|a pinch; Sesame seeds|1-2 tbsp; Maida|2-3 tbsp; Oil|for frying; Pita bread|to serve; Salt|to taste',
    method: [
      'Tahini: lightly toast sesame seeds, then blend them warm, adding olive oil gradually, to a smooth paste; salt it.',
      'Soak all the chickpeas for 7-8 hours or overnight.',
      'Hummus: pressure-cook half the chickpeas with salt for 3-4 whistles; blend with some cooking water, an ice cube and garlic till fine, then add tahini, salt, lemon and olive oil and blend smooth.',
      'Falafel: pulse the other half (soaked, not cooked) with onion, garlic, chillies, herbs, spring onion greens, spices and sesame in short bursts to a coarse mix; add a little olive oil and the flour.',
      'Shape small patties and fry till crisp and golden. Serve with hummus and pita.',
    ],
  },
  'Veg Burrito Bowl': {
    from: 'description',
    ingredients: 'Paneer|300 g; Capsicum|1 cup, mixed colours; Onion|3 large; Rajma|½ cup, soaked and cooked; Cinnamon|1 stick; Garlic|2 tbsp + 4 cloves; Jalapeño|2 (or green chilli); Tomato|2; Rice|3 cups, cooked; Butter|2 tbsp; Coriander leaves|2 handfuls; Lemon|1½; Sweet corn|⅓ cup, boiled; Curd|¾ cup, thick; Tomato ketchup|2 tbsp; Red chilli sauce|1 tbsp; Lettuce|shredded; Avocado|diced; Tortillas|optional, for burritos; Processed cheese|optional; Oil|2 tbsp; Red chilli powder|1 tbsp; Cumin powder|2 tsp; Coriander powder|1 tsp; Oregano|2 tsp; Garlic powder|2 tsp; Onion powder|2 tsp; Salt|to taste',
    method: [
      'Mix the spice powders with 1 tsp salt to make the Mexican seasoning.',
      'Stir-fry 1 onion, the peppers and paneer on high heat with 1½ tbsp seasoning, lemon and salt for 2-3 minutes.',
      'Refried beans: pressure-cook the soaked rajma with a cinnamon stick for 5 whistles. Fry onion, garlic and jalapeño till light golden, add grated tomato, 1 tbsp seasoning and a splash of hot water, then the beans; simmer till thick.',
      'Rice: toss the cooked rice in butter with coriander, lemon and salt for 2-3 minutes.',
      'Pico de gallo: mix chopped onion, tomato, jalapeño, coriander, lemon, salt and corn.',
      'Sauce: mix the curd, ketchup, chilli sauce, lemon, 1 tsp seasoning and grated garlic.',
      'Build the bowl: rice, beans, lettuce, paneer and peppers, pico de gallo, avocado and sauce (or roll it all in a tortilla).',
    ],
  },
  'Thai Green Curry': {
    from: 'description',
    ingredients: 'Thai green curry paste|half a batch (the video makes it fresh); Coconut milk|1 litre; Baby corn|½ cup; Mushroom|½ cup; Broccoli|½ cup; Carrot|½ cup; Capsicum|⅓ cup green + ⅓ cup red; Brown sugar|1½-2 tbsp; Kaffir lime leaves|2-3; Thai basil|a small handful; Red chilli|1-2, sliced; Salt|to taste; Rice|to serve',
    method: [
      'Paste (or use ready-made): toast coriander and cumin seeds and grind with white pepper, then pound or blend with galangal, fresh turmeric, lemongrass, garlic, shallots, green chillies, kaffir lime zest, coriander roots and stems, and salt. Half goes into this curry; the rest keeps in the fridge.',
      'Boil 200 ml coconut milk for a few minutes till it thickens, then fry the paste in it for 4-5 minutes till it darkens and the fat separates.',
      'Add the rest of the coconut milk and bring to a boil.',
      'Cook the baby corn for 2-3 minutes, then add the other vegetables, sugar and salt; thin with stock if needed.',
      'Add the lime leaves, Thai basil and red chilli and cook 2-3 minutes more. Serve with rice.',
    ],
  },
  'Veg Pad Thai': {
    from: 'description',
    ingredients: 'Fried tofu|115 g; Broccoli|70 g; Carrot|½; Red onion|½; Chinese chives|35 g (or spring onion greens); Rice noodles|115 g, thin; Tamarind paste|2 tbsp; Maple syrup|1 tbsp (or honey or sugar); Soy sauce|2 tbsp; Red chilli|1, sliced; Olive oil|a drizzle; Bean sprouts|50 g; Peanuts|2 tbsp, roasted; Coriander leaves|a few sprigs; Lime|wedges, to serve',
    method: [
      'Soak the rice noodles in just-boiled water for 2-3 minutes, stirring to loosen them; drain.',
      'Slice the tofu, cut the broccoli small and the carrot into matchsticks, slice the onion and chop the chives.',
      'Mix the tamarind, maple syrup, soy sauce and sliced chilli for the sauce.',
      'Sauté the onion in a little oil, add the tofu and broccoli for a few minutes, then the carrot.',
      'Add the noodles, chives, bean sprouts and sauce; toss for a few minutes.',
      'Top with crushed peanuts and coriander; serve with lime.',
    ],
  },
  'Tofu Stir-fry': {
    from: 'description',
    ingredients: 'Tofu|cubed, lightly fried; Mushroom|chopped; Carrot|chopped; Broccoli|florets; Baby corn|a few; Capsicum|chopped; Zucchini|chopped; Onion|1 medium, cubed; Garlic|3-4 cloves; Green chilli|to taste; Soy sauce|2 tbsp; Vinegar|2 tsp; Brown sugar|2 tsp; Black pepper|crushed; Oil|for cooking; Salt|to taste',
    method: [
      'Mix the soy sauce, vinegar and brown sugar with crushed pepper and salt; keep aside.',
      'Heat oil; add the garlic and green chillies, then the mushrooms.',
      'Add the carrot, baby corn and broccoli, then the onion; cook 5-7 minutes till lightly golden.',
      'Add the tofu, zucchini and peppers.',
      'Pour in the sauce and cook about 5 minutes more.',
    ],
  },
  'Veg Hakka Noodles': {
    from: 'description',
    ingredients: 'Noodles|150 g (1 packet); Oil|as needed; Garlic|1 tbsp; Onion|⅓ cup; Carrot|⅓ cup; Capsicum|⅓ cup; Cabbage|⅓ cup; Sugar|a pinch; Green chilli paste|¼ tsp; Spring onion|a small handful of greens; White pepper powder|a pinch; Soy sauce|½ tsp (light); Vinegar|½ tsp; Aromat powder|a pinch (optional); Salt|to taste',
    method: [
      'Boil the noodles in salted water with a little oil for just 30 seconds, turn off the heat and leave them covered for 2-2½ minutes; rinse in cold water and toss with a little oil.',
      'Cut the vegetables into thin strips (the video shows the knife work).',
      'In a very hot wok with 1 tbsp oil, toss the garlic and all the vegetables for 30 seconds.',
      'Add the sugar, chilli paste, spring onion greens, noodles and seasonings; toss for 1-1½ minutes.',
      'Garnish with spring onion greens.',
    ],
  },
  'Veg Fried Rice': {
    from: 'description',
    ingredients: 'Rice|500 g; Oil|4 tbsp; Spring onion|¼ cup bulbs + ¼ cup greens + to garnish; Ginger garlic paste|1 tbsp; Green chilli paste|1 tbsp; Carrot|⅓ cup; Cabbage|1 cup; Capsicum|⅓ cup; Beans|¼ cup; Sugar|1 tsp; Paneer|150 g, small dice; Soy sauce|1 tbsp; Red chilli sauce|1 tbsp; Vinegar|1 tsp; Black pepper|to taste; Salt|to taste',
    method: [
      'Rinse and soak the rice for 15 minutes, then boil it in plenty of salted water with a little oil till 80-90% done (8-10 minutes); drain.',
      'On high heat, stir-fry the spring onion bulbs and ginger-garlic paste for a minute.',
      'Add the spring onion greens, chilli paste, vegetables and sugar; toss for 2-3 minutes.',
      'Add the paneer, then the sauces, salt and pepper, for a minute.',
      'Fold in the rice for 2 minutes and finish with vinegar and spring onion greens.',
    ],
  },
  'Chilli Paneer': {
    from: 'description',
    ingredients: 'Paneer|250 g; Cornflour|¼ cup + 5 tbsp; Oil|about 6 tbsp; Garlic|13-15 cloves; Ginger|1 inch; Green chilli|8-10; Spring onion|5-6 bulbs + ¼ cup greens + to garnish; Capsicum|2 medium; Sugar|1 tsp; Soy sauce|2 tbsp; Red chilli sauce|2 tbsp; Black pepper|to taste; Salt|to taste',
    method: [
      'Toss the paneer with salt, pepper and ¼ cup cornflour; shallow-fry till golden on all sides.',
      'On high heat, stir-fry the garlic, ginger, slit chillies and spring onion bulbs for 3-4 minutes.',
      'Add the capsicum, spring onion greens and sugar for a minute, then the soy and chilli sauces.',
      'Stir in 5 tbsp cornflour mixed with 100 ml water and cook till the sauce thickens; season.',
      'Fold in the paneer, finish with spring onion greens and serve straight away.',
    ],
  },
  'Veg Manchurian': {
    from: 'description',
    ingredients: 'Cabbage|1 cup; Carrot|½; Beans|½ cup; Spring onion|¼ cup greens + 2 tbsp bulbs + 2 tbsp greens; Coriander leaves|2 tbsp + a handful + 1 tsp stems; Ginger|2 inch; Garlic|6 tbsp, chopped; Green chilli|1-2; Green chilli paste|2 chillies + 2-3 tsp; Soy sauce|1 tsp light + 1 tbsp dark; Red chilli sauce|1 tbsp; Butter|1 tbsp; White pepper powder|2 pinches; Sugar|2 pinches; Cornflour|7 tbsp; Maida|3 tbsp; Oil|for frying + 2 tbsp; Onion|2 tbsp; Capsicum|2 tbsp; Vinegar|1 tsp; Veg stock|100-150 ml (or hot water); Salt|to taste',
    method: [
      'Lightly mix the chopped vegetables with ginger, garlic, chilli paste, sauces, butter and seasoning by hand, then add the cornflour and maida bit by bit till a small portion holds as a ball.',
      'Shape small balls with wet fingers and fry, first in hot oil and then on medium-low for 3-4 minutes, till light golden; rest 5-7 minutes.',
      'Re-fry briefly in very hot oil till crisp.',
      'Sauce: on high heat, toss the onion, garlic, ginger, coriander stems, chillies and capsicum for 1-2 minutes; add the stock, chilli paste, dark soy, vinegar, pepper, salt and sugar and bring to a boil.',
      'Thicken with 1 tbsp cornflour mixed in 2 tbsp water.',
      'Toss in the fried balls with coriander and spring onions.',
    ],
  },
  // ---- Added later (30 more). Ingredients from each video's description; methods summarised. ----
  'Shahi Paneer': {
    from: 'description',
    ingredients: 'Ghee|1 tbsp; Oil|1 tbsp; Cumin seeds|1 tsp; Cinnamon|1 inch; Cloves|2; Green cardamom|2; Black cardamom|1; Bay leaf|1; Green chilli|2; Ginger garlic paste|1 tbsp; Onion|2 medium; Cashews|10-12, soaked; Tomato|4 medium; Turmeric|¼ tsp; Butter|2 tbsp; Kashmiri red chilli powder|1 tbsp; Coriander powder|1 tsp; Paneer|250 g; Cream|¼ cup + to garnish; Kasuri methi|1 tsp; Cardamom powder|a pinch; Salt|to taste',
    method: [
      'Heat ghee and oil; crackle cumin with cinnamon, cloves, both cardamoms and the bay leaf, then add the green chillies and ginger-garlic paste.',
      'Add the onions and soaked cashews and cook without letting them brown.',
      'Add tomatoes, salt and turmeric, then ½ cup water; cover and cook on low for 12-15 minutes. Let it cool.',
      'Blend smooth and strain for a silky gravy.',
      'In butter, cook the Kashmiri chilli and coriander powder for a minute, add the gravy, then the paneer.',
      'Stir in the cream and crushed kasuri methi and simmer 2 minutes. Garnish with cream and a pinch of cardamom powder.',
    ],
  },
  'Dum Aloo': {
    from: 'description',
    ingredients: 'Potato|5-6 large, diced; Onion|4-5 medium, sliced; Oil|¼ cup + 2-3 tbsp; Ghee|¼ cup; Curd|1½ cups, beaten; Tamarind paste|1 tbsp; Degi red chilli powder|1 tbsp; Coriander leaves|2 tbsp + 1 tbsp stems + to garnish; Ginger|1 inch, julienned; Green chilli|2-3; Sesame seeds|2 tbsp; Cashews|10-12; Black peppercorns|1 tsp; Coriander seeds|2 tsp; Cumin seeds|½ tsp; Cloves|5-6; Black cardamom|1; Green cardamom|5; Mace|1 blade; Dry red chilli|4-5 Byadgi + 2-3 for the tadka; Salt|to taste',
    method: [
      'Masala: dry-roast the sesame, cashews, peppercorns, coriander seeds, cumin, cloves, both cardamoms, mace and Byadgi chillies for 2-3 minutes, then grind fine.',
      'Fry the potatoes in oil and ghee till half cooked, add the onions and salt and cook 7-8 minutes till golden; set aside.',
      'Mix ¼ cup of the masala with the curd, tamarind, chilli powder, salt, coriander stems and leaves, ginger, green chillies and 1½ cups water.',
      'Combine with the potatoes in the pot, cover and cook on low-medium for 15-20 minutes; loosen with a little water and bring to a boil.',
      'Top with dry chillies fried crisp in oil, and coriander. Serve with roti.',
    ],
  },
  'Methi Malai Matar': {
    from: 'description',
    ingredients: 'Oil|1 tbsp; Ginger|1 inch; Onion|2-3 medium; Curd|2 cups; Cashews|about 25; Ghee|3-4 tbsp; Hing|a pinch; Green cardamom|3-5; Green chilli|1-2; Butter|1 tbsp; Peas|½ cup; Methi leaves|1 cup, fresh; Cumin seeds|½ tsp; Black peppercorns|1 tbsp; Kasuri methi|2 tbsp; Dry red chilli|1; Degi red chilli powder|½ tsp; Cream|to garnish; Coriander leaves|to garnish; Salt|to taste',
    method: [
      'Blanch 15-18 cashews briefly in salted boiling water; drain.',
      'Sauté the ginger and onions with salt in oil till translucent; add the curd and cook on low for 2-4 minutes.',
      'Add the cashews and some water, blend smooth, simmer 5-10 minutes and strain.',
      'Toss the peas and fresh methi in butter for 4-5 minutes.',
      'Masala: dry-roast salt, cardamom, cumin and peppercorns, add the kasuri methi, and grind.',
      'Heat ghee with hing and cardamom seeds, add the gravy, green chilli, and the peas and methi; cook 2-3 minutes.',
      'Tadka: fry a dry chilli and the remaining cashews in ghee with degi chilli. Pour it over, and finish with a sprinkle of the masala, cream and coriander.',
    ],
  },
  'Sarson ka Saag': {
    from: 'description',
    ingredients: 'Mustard greens|6 cups, chopped; Amaranth leaves|1 cup; Chickpea leaves|1½ cups; Turnip|2; Ginger|1 inch; Garlic|2-3 cloves + 1 tbsp chopped; White butter|6 tbsp; Green chilli|1; Red chilli powder|¼ tsp; Turmeric|¼ tsp; Ghee|¼ cup; Dry red chilli|1; Cumin seeds|⅛ tsp; Onion|to serve; Jaggery|to serve; Makki ki roti|to serve; Salt|to taste',
    method: [
      'Put the chopped greens, turnips, ginger, garlic cloves, 2 tbsp white butter, green chilli, salt, chilli powder and turmeric in a pan with water; cook on low for about 2 hours.',
      'Churn or mash it to a coarse purée.',
      'Heat the ghee, crackle the dry chilli and cumin, and cook the chopped garlic till translucent.',
      'Mix in the saag and top with white butter.',
      'Serve with makki ki roti, onion, more butter and a little jaggery.',
    ],
  },
  'Chana Dal Fry': {
    from: 'description',
    ingredients: 'Chana dal|3 cups, boiled; Ghee|3 tbsp; Hing|½ tsp; Dry red chilli|2; Cumin seeds|1 tsp; Garlic|1 tbsp, chopped; Green chilli|2; Onion|¼ cup; Ginger|2 tsp, chopped; Turmeric|½ tsp; Red chilli powder|1 tsp; Tomato|¼ cup; Coriander leaves|to garnish; Lemon|1 wedge; Salt|to taste',
    method: [],
  },
  'Kala Chana Masala': {
    from: 'description',
    ingredients: 'Kala chana|2 cups, soaked; Cinnamon|1 inch; Bay leaf|2; Black cardamom|1; Green cardamom|4; Mace|1; Black peppercorns|12; Cumin seeds|1 tsp; Ginger paste|1 tbsp; Garlic|2½ tbsp; Green chilli|6-7; Onion|1 cup; Tomato|1 cup, puréed; Turmeric|1 tsp; Red chilli powder|1 tbsp; Coriander powder|1 tbsp; Cumin powder|1½ tbsp; Garam masala|½ tsp; Coriander leaves|¼ cup; Oil|¼ cup; Ghee|2 tbsp; Salt|to taste',
    method: [],
  },
  'Lauki Chana Dal': {
    from: 'description',
    ingredients: 'Lauki|500 g; Chana dal|⅓ cup; Onion|½ cup; Tomato|1 cup; Ginger garlic paste|½ tbsp; Green chilli|2; Bay leaf|1; Cumin seeds|1 tsp; Black cardamom|1; Turmeric|½ tsp; Red chilli powder|1 tsp; Cumin powder|½ tsp; Coriander powder|1 tsp; Garam masala|1 tsp; Coriander leaves|4 tbsp; Oil|4 tbsp; Salt|to taste',
    method: [],
  },
  'Gobi Paratha': {
    from: 'description',
    ingredients: 'Cauliflower|400 g; Garlic|12 cloves; Green chilli|4; Ginger|3 inch; Cumin seeds|½ tsp; Hing|¼ tsp; Turmeric|½ tsp; Red chilli powder|½ tsp; Garam masala|½ tsp; Coriander leaves|4 tbsp; Oil|2 tbsp + to cook; Atta|2 cups; Salt|to taste',
    method: [],
  },
  'Paneer Paratha': {
    from: 'description',
    ingredients: 'Paneer|2 cups, grated (the video makes it from 1 litre full-fat milk and 4 tbsp lemon juice); Atta|2 cups; Onion|2 tbsp, finely chopped; Green chilli|1; Coriander seeds|1½ tbsp, pounded; Cumin seeds|1 tsp; Ginger|a little, chopped; Anardana|1 tbsp, pounded; Red chilli powder|1 tsp; Garam masala|¼ tsp; Salt|to taste',
    method: [],
  },
  'Gatte ki Sabzi': {
    from: 'description',
    ingredients: 'Besan|½ cup + 1 tsp; Red chilli powder|¾ tsp; Turmeric|¾ tsp; Coriander powder|½ tsp; Baking soda|2 pinches; Oil|2 tbsp + 1 tsp; Tomato|2 (125 g); Cumin seeds|1 tsp; Green chilli|1-2; Ginger|½ inch; Hing|½ pinch; Curd|¼ cup; Garam masala|¼ tsp; Salt|to taste',
    method: [],
  },
  'Mirchi ka Salan': {
    from: 'description',
    ingredients: 'Long green chillies|about 10; Peanuts|30 g; Sesame seeds|15 g; Coconut powder|1 tbsp; Oil|30 ml; Dry red chilli|3; Mustard seeds|½ tsp; Cumin seeds|½ tsp; Fenugreek seeds|a pinch; Onion|1; Hing|a pinch; Turmeric|¼ tsp; Ginger garlic paste|1 tbsp; Curry leaves|8; Red chilli powder|½ tsp; Coriander powder|1 tbsp; Cumin powder|1 tsp; Curd|100 g, beaten; Tamarind|30 g pulp; Jaggery|a little (or sugar); Salt|to taste',
    method: [
      'Fry the peanuts in a little oil on low heat, add the sesame and roast till golden, then the coconut for a few seconds; blend with water to a fine paste.',
      'Heat the rest of the oil; add whole red chillies, then mustard, cumin and fenugreek seeds.',
      'Cook the onion with a little salt till golden brown, then add hing, turmeric, ginger-garlic paste and curry leaves.',
      'Add a splash of water and the chilli, coriander and cumin powders; cook till the oil separates.',
      'Add more water, the curd and the nut paste; cover and cook, stirring, till the oil shows.',
      'Add the tamarind and jaggery and simmer 15-20 minutes, then the slit green chillies for 5-10 minutes more. Adjust the salt.',
    ],
  },
  'Medu Vada': {
    from: 'description',
    ingredients: 'Urad dal|200 g; Onion|1 cup, chopped; Cumin seeds|1 tsp; Black pepper|1 tsp; Coriander leaves|1 bunch; Hing|a pinch; Oil|for frying; Salt|to taste',
    method: [
      'Soak the urad dal for 6 hours or overnight, then grind to a coarse batter.',
      'Mix in the onion, cumin, pepper, coriander, hing and salt.',
      'Shape into rings with a hole in the middle and deep-fry till golden.',
    ],
  },
  'Lemon Rice': {
    from: 'description',
    ingredients: 'Rice|100 g, cooked; Cashews|10 g; Peanuts|10 g; Chana dal|10 g; Urad dal|10 g; Mustard seeds|5 g; Dry red chilli|5 g; Green chilli|5 g; Ginger|1 slice; Hing|a pinch; Turmeric|a pinch; Curry leaves|a sprig; Lemon|20 ml juice; Oil|10 ml; Coriander leaves|a sprig; Salt|to taste',
    method: [
      'Rinse and soak the rice for about 30 minutes, then boil in plenty of salted water till just done; drain.',
      'Heat oil with hing and mustard seeds, add the broken dry chillies, urad and chana dal, ginger and nuts, and fry till the dals turn light brown.',
      'Add curry leaves and turmeric for half a minute.',
      'Stir in the rice, salt and lemon juice; garnish with coriander.',
    ],
  },
  'Bisi Bele Bath': {
    from: 'description',
    ingredients: 'Rice|1 cup; Toor dal|½ cup; Mixed vegetables|2 cups (carrot, beans, radish, shallots, tomato, drumstick); Onion|1; Tamarind|20 g, as juice; Chana dal|1 tsp; Urad dal|1 tsp; Coriander seeds|1 tsp; Cumin seeds|1 tsp + for tempering; Dry red chilli|4; Cinnamon|1 inch; Cloves|2; Green cardamom|2; Coconut|1 tbsp, desiccated; Cashews|2 tsp, broken; Turmeric|¼ tsp; Hing|a pinch; Mustard seeds|½ tsp; Curry leaves|a few sprigs; Oil|1 tsp; Coriander leaves|to garnish; Ginger garlic paste|optional; Salt|to taste',
    method: [
      'Wash the toor dal and cook it along with the rice.',
      'Roast the whole spices, dals, chillies and cashews, then grind with the coconut and turmeric (and ginger-garlic, if using) into a powder.',
      'Heat oil, splutter cumin, mustard and curry leaves, soften the onion, then lightly fry the other vegetables.',
      'Add the cooked rice and dal, the spice powder, tamarind juice and salt, and cook till everything is done and comes together.',
      'Garnish with coriander and serve hot.',
    ],
  },
  'Avial': {
    from: 'description',
    ingredients: 'Mixed vegetables|2 cups (yam, raw banana, potato, drumstick, beans, carrot, ash gourd); Coconut|½ cup, grated; Green chilli|2; Cumin seeds|2 tsp; Curd|½ cup, thick; Coconut oil|2 tbsp; Curry leaves|2 sprigs; Rice flour|1 tbsp; Turmeric|1 tsp; Salt|to taste',
    method: [
      'Cook the vegetables in a little water with salt and turmeric till done.',
      'Grind the coconut, green chillies and cumin to a fine paste and stir it in.',
      'Thicken with the rice flour mixed smooth in a little water, and bring to a boil; it should be thick.',
      'Finish with curry leaves, coconut oil and the thick curd.',
    ],
  },
  'Vada Pav': {
    from: 'description',
    ingredients: 'Besan|3 cups; Ajwain|a pinch (optional); Baking soda|a pinch (optional); Potato|8-10 medium, boiled; Garlic|about 20 cloves; Ginger|about 1 inch; Green chilli|10-12 + a few to fry; Coriander leaves|2 handfuls; Oil|2 tbsp + for frying; Mustard seeds|¼ tsp; Cumin seeds|½ tsp; Hing|¼ tsp; Curry leaves|8-10; Turmeric|½ tsp; Garam masala|a pinch; Lemon|1 tbsp juice; Red chilli powder|2 tbsp; Pav|to serve; Sweet chutney|to serve; Onion|chopped, to serve; Salt|to taste',
    method: [
      'Whisk the besan with salt, ajwain, soda and water for 4-5 minutes into a smooth, flowing batter; rest 15-20 minutes.',
      'Grind garlic, ginger, green chillies and a pinch of salt into a coarse paste (kharda), and coriander, chillies, garlic, ginger and salt with a little water into thecha.',
      'Crackle cumin and mustard in oil, add hing, curry leaves and the kharda for 1-2 minutes, then turmeric, garam masala and salt.',
      'Add the mashed potatoes and cook 2-3 minutes, then lemon and coriander for a few minutes more; let it cool.',
      'Red chutney: drizzle batter into hot oil to make crisp bits, briefly fry garlic cloves, then grind both with salt and chilli powder.',
      'Shape the potato into flat balls, coat in batter and deep-fry till crisp and golden.',
      'Serve in pav with thecha, sweet chutney, red chutney, onion and fried salted chillies.',
    ],
  },
  'Misal Pav': {
    from: 'description',
    ingredients: 'Moth beans|1 cup, sprouted; Coconut|½ cup, grated; Coriander seeds|2 tbsp; Dry red chilli (Kashmiri)|7-8; Oil|5 tbsp; Onion|3 medium; Ginger|1 inch; Garlic|5-6 cloves; Tomato|1 medium; Turmeric|½ tsp; Mustard seeds|1 tsp; Cumin seeds|1 tsp; Curry leaves|7-8; Red chilli powder|1 tbsp; Goda masala|1 tbsp; Jaggery|1 tsp; Farsan|to top; Pav|to serve; Lemon|to serve; Salt|to taste',
    method: [
      'Dry-roast the coconut till golden, and the Kashmiri chillies and coriander seeds for 3-4 minutes.',
      'In 1 tbsp oil, cook the onions, ginger and garlic till light brown, then the tomato till mushy; cool, and grind with the roasted coconut and spices to a paste.',
      'Pressure-cook the sprouted moth beans with salt, turmeric and 250 ml water for one whistle.',
      'Heat 4 tbsp oil, splutter mustard and cumin, add curry leaves and the paste, and cook till the oil separates.',
      'Add the chilli powder and goda masala for 3-4 minutes, then the beans, about 750 ml water, salt and jaggery; simmer 10-15 minutes till oil rises to the top.',
      'Serve topped with farsan, with pav, chopped onion and lemon.',
    ],
  },
  'Paneer Kathi Roll': {
    from: 'description',
    ingredients: 'Maida|2 cups + for dusting; Sugar|1½ tbsp; Ghee|2 tbsp + for brushing; Mustard oil|2 tbsp; Kashmiri red chilli powder|1 tbsp; Garam masala|½ tsp; Black salt|¼ tsp; Ginger garlic paste|1 tbsp; Lemon|1 tsp juice; Curd|⅓ cup; Paneer|250 g; Onion|⅓ cup, sliced; Capsicum|⅓ cup; Tomato|⅓ cup; Red chilli powder|a pinch; Oil|for cooking; Salt|to taste',
    method: [
      'Mix the maida, sugar and 1 tsp salt, rub in the ghee, add warm water gradually and knead 10-12 minutes till soft and smooth; oil, cover and rest at least an hour.',
      'Whisk the mustard oil with Kashmiri chilli, then add garam masala, black salt, ginger-garlic paste, lemon, curd and salt; coat the paneer cubes.',
      'Sear the paneer on high heat for 2-3 minutes, stirring little, then toss in the onion, capsicum, tomato and a pinch of chilli for 1-2 minutes.',
      'Roll a dough ball thin, brush with ghee, dust with flour, pleat and coil it, then roll it out again for a layered paratha.',
      'Cook on a hot pan, first dry and then with a little oil, till spotted and cooked through.',
      'Fill with the paneer and roll up.',
    ],
  },
  'White Sauce Pasta': {
    from: 'description',
    ingredients: 'Pasta|200 g penne; Oil|1 tbsp + 1 tsp; Butter|30 g; Maida|30 g; Milk|400 ml; Black pepper|2 pinches; Oregano|½ tsp; Nutmeg|a pinch; Processed cheese|50 g; Salt|to taste',
    method: [
      'Boil the penne in salted water with 1 tsp oil for 7-8 minutes, till al dente; drain and toss with 1 tbsp oil, salt and pepper.',
      'Melt the butter on medium-low and cook the maida for 2-3 minutes without letting it brown.',
      'Whisk in the milk in three goes to a smooth sauce; season with salt, pepper, oregano and nutmeg.',
      'Stir in the processed cheese till it melts.',
      'Add the pasta and cook 2 minutes. (The same video also shows red and pink sauce versions.)',
    ],
  },
  'Veg Khao Suey': {
    from: 'description',
    ingredients: 'Coconut|2 cups fresh (for 800 ml coconut milk); Onion|2 medium + sliced to serve; Garlic|6-7 cloves; Ginger|1 inch; Green chilli|1-2; Coriander leaves|1 tbsp stems + to garnish; Oil|1 tbsp; Turmeric|2 tsp; Red chilli powder|2 tsp; Coriander powder|1 tsp; Cumin powder|1 tsp; Beans|½ cup; Carrot|½ cup; Baby corn|½ cup; Veg stock|750 ml (or hot water); Jaggery|1 tbsp; Besan|1 tbsp; Lemon|to finish + wedges; Noodles|boiled, to serve; Peanuts|roasted, crushed; Spring onion|greens, to top; Fried onions|to top; Chilli oil|to top; Salt|to taste',
    method: [
      'Coconut milk: blend the fresh coconut with water, squeeze it through muslin, then blend the pulp again with more water and squeeze (about 800 ml).',
      'Grind the onion, garlic, ginger, green chillies and coriander stems to a paste; cook it in oil for 2-3 minutes.',
      'Lower the heat, add the spice powders with a splash of water, and cook till the oil shows.',
      'Add the vegetables, stock, jaggery and salt; boil 5-6 minutes.',
      'Whisk the besan smooth with a little coconut milk, stir it into the rest, and add to the pot; simmer 5-6 minutes, stirring. Finish with lemon.',
      'Serve over boiled noodles, topped with peanuts, sliced onion, fried noodles, fried onions and garlic, coriander, spring onion, chilli oil and lemon.',
    ],
  },
  'Thai Red Curry': {
    from: 'description',
    ingredients: 'Thai red curry paste|half a batch (the video makes it fresh); Coconut milk|500 ml; Baby corn|⅓ cup; Carrot|⅓ cup; Mushroom|⅓ cup; Broccoli|⅓ cup, blanched; Capsicum|⅓ cup green + ⅓ cup red; Brown sugar|1½ tbsp; Basil|a large handful; Kaffir lime leaves|6-7; Red chilli|1-2, sliced; Salt|if needed; Rice|to serve',
    method: [
      'Paste (or use ready-made): grind coriander seeds, cumin and white pepper; pound lemongrass, galangal, lime leaves, garlic, shallots, coriander stems and roots, lemon peel and salt to a paste; add soaked Kashmiri and hot red chillies and grind smooth, then mix in the spice powder. Half goes into this curry.',
      'Boil 100 ml coconut milk, add the paste and cook on medium-high till the oil comes out.',
      'Add the rest of the coconut milk and 500-600 ml water; bring to a boil.',
      'Cook the baby corn for 3-4 minutes, then the other vegetables on high for 2-3 minutes.',
      'Season, add the brown sugar, basil and lime leaves for 1-2 minutes, and finish with sliced red chilli. Serve with rice.',
    ],
  },
  'Veg Spring Rolls': {
    from: 'description',
    ingredients: 'Oil|2 tbsp + for frying; Garlic|2 tbsp; Ginger|2 tbsp; Spring onion|2 tbsp bulbs + greens; Onion|½ cup; Carrot|1 cup; Capsicum|1 cup; Cabbage|1 cup; White pepper powder|a pinch; Green chilli paste|2 tsp; Red chilli sauce|1 tbsp; Tomato ketchup|2 tbsp; Soy sauce|2 tsp; Kashmiri chilli paste|2 tsp; Vinegar|1 tsp; Sugar|1 tsp; Cornflour|150 g + ½ tsp; Maida|150 g + 2 tbsp; Salt|to taste',
    method: [
      'Filling: on high heat, cook garlic, ginger and spring onion bulbs in oil for 1-2 minutes, add the vegetables, sauces, pastes and seasoning for 1-2 minutes more, sprinkle ½ tsp cornflour, add spring onion greens and let it cool.',
      'Sheets (or use ready ones): whisk maida, cornflour, salt and about 475 ml water into a thin batter that coats a spoon; rest 12-15 minutes.',
      'On a moderately hot non-stick pan, pour a ladleful and swirl into a thin sheet; cook 30-40 seconds and lift off. Stack with cornflour in between, covered.',
      'Roll the filling tightly in the sheets and seal with a paste of 2 tbsp maida and water.',
      'Deep-fry till golden and crisp.',
    ],
  },
  'Schezwan Fried Rice': {
    from: 'description',
    ingredients: 'Dry red chilli (Kashmiri)|10-15, soaked; Oil|5 tbsp; Basmati rice|1 cup (sella); Onion|¼ cup; Garlic|2 tbsp; Ginger|1 inch; Green chilli|1 tsp, chopped; Coriander leaves|1 tbsp stems; Carrot|⅓ cup; Beans|⅓ cup; Spring onion|¼ cup bulbs + greens; White pepper powder|a pinch; Sugar|a pinch; Vinegar|1 tsp; Tomato ketchup|1 tsp; Salt|to taste',
    method: [
      'Chilli paste: grind the soaked Kashmiri chillies smooth and cook in 4 tbsp oil on high, stirring, till the oil separates; cool and keep in a jar.',
      'Rinse and soak the rice for 15 minutes, boil in salted water till almost done, drain, fluff and spread out to cool.',
      'In a very hot wok with 1 tbsp oil, cook the onion, garlic, ginger, green chilli and coriander stems for a minute.',
      'Add the carrots, beans and spring onion bulbs, and cook till just done but still crunchy.',
      'Add the rice, salt, white pepper, sugar, vinegar, 1 tbsp chilli paste, ketchup and spring onion greens; toss on high for a minute.',
    ],
  },
  'Hot and Sour Soup': {
    from: 'description',
    ingredients: 'Cabbage|½; Carrot|1; Capsicum|1; Beans|8-10; Mushroom|2-3 large; Spring onion|2 handfuls; Oil|2 tbsp; Ginger|1 tbsp; Garlic|1 tbsp; Veg stock|800-900 ml (or hot water); Green chilli paste|from 2 chillies; Sugar|a pinch; Soy sauce|2 tsp (dark); Vinegar|2 tbsp; Red chilli sauce|1 tbsp; White pepper powder|a pinch; Cornflour|2 tbsp; Coriander leaves|a handful; Salt|to taste',
    method: [
      'Cut all the vegetables into thin strips and chop the spring onion greens.',
      'Heat oil in a hot wok; cook the ginger and garlic on low for 30 seconds, then the mushrooms on high for a minute.',
      'Add the rest of the vegetables and toss on high for a minute.',
      'Add the stock, chilli paste, sugar, soy sauce, vinegar, chilli sauce, white pepper and salt; bring to a boil.',
      'Thicken with cornflour mixed in water, adding only as much as you need for a semi-thick soup.',
      'Stir in coriander and spring onion greens, and adjust the seasoning.',
    ],
  },
  'Sweet Corn Soup': {
    from: 'description',
    ingredients: 'Sweet corn|2 cups (300 g); Sugar|a large pinch (optional); White pepper powder|¼ tsp; Vinegar|¼ tsp; Soy sauce|½ tsp (light); Carrot|1 small; Beans|15; Capsicum|1 small; Cornflour|1-2 tbsp (optional); Paneer|100-150 g; Spring onion|a handful of greens; Salt|to taste',
    method: [
      'Boil the corn for 4-5 minutes, till it floats; drain and split in half.',
      'Blend one half with water to a fine purée.',
      'Bring the purée and 1-1½ litres hot water to a boil, then simmer 7-8 minutes, skimming off any scum.',
      'Add salt, sugar, white pepper, vinegar, soy sauce, the vegetables and the rest of the corn; cook 4-5 minutes.',
      'Thicken with a little cornflour slurry if you like, and finish with diced paneer and spring onion greens.',
    ],
  },
  'Paneer Tikka Tacos': {
    from: 'description',
    ingredients: 'Paneer|250 g; Curd|½ cup thick + 1 cup; Ginger garlic paste|1 tbsp; Red chilli powder|1 tbsp; Coriander powder|1 tbsp; Cumin powder|1 tsp; Turmeric|¼ tsp; Amchur|1 tsp; Garam masala|1½ tsp; Oil|2 tbsp + for the shells; Cumin seeds|2 tsp; Onion|2 medium; Green chilli|1-2; Tomato purée|½ cup; Tomato|1 medium; Capsicum|1 medium; Kasuri methi|1 tsp; Coriander leaves|1 tbsp + for the shells; Maida|2 cups; Baking powder|1 tsp; Kalonji|a pinch; Salt|to taste',
    method: [
      'Marinate the paneer in thick curd, ginger-garlic paste, the spice powders and salt for 15-20 minutes.',
      'Fry cumin in oil, cook one chopped onion till translucent, then the green chillies and tomato purée for 3-4 minutes.',
      'Add 100 ml water and salt, then the paneer; cook 5-6 minutes.',
      'Add the diced tomato, capsicum and the other onion for 3-4 minutes; finish with kasuri methi, garam masala and coriander.',
      'Shells: mix maida, salt and baking powder, add 1 cup curd and water to a soft dough, and rest 30 minutes.',
      'Pat out small rounds, sprinkle kalonji and coriander, wet the underside and stick it to a hot tawa; turn the tawa over the flame to char the top, like tawa naan.',
      'Fill the shells with the paneer.',
    ],
  },
  'Potato Au Gratin': {
    from: 'description',
    ingredients: 'Potato|5-6 medium (2 cubed and boiled, 3-4 sliced and parboiled); Butter|4 tbsp; Paprika|½ tsp; Nutmeg|a pinch; Cream|1 tbsp; Oil|1 tbsp; Onion|2 medium; Black peppercorns|½ tsp, crushed; Chives|a few; Processed cheese|1 cup, grated; Parsley|to garnish; Salt|to taste',
    method: [
      'Preheat the oven to 180°C.',
      'Mash the boiled potato cubes in a pan over heat with 2 tbsp butter, the paprika, salt, nutmeg and cream; spread in a baking dish.',
      'Sauté the onions in oil with salt and crushed pepper till translucent, add chopped chives, and spread over the mash.',
      'Cover with the parboiled potato slices, drizzle with the remaining butter, melted, top with cheese and press lightly.',
      'Bake 10-15 minutes till golden; garnish with parsley.',
    ],
  },
  'Bruschetta': {
    from: 'description',
    ingredients: 'Sourdough bread|4 slices; Butter|1 tbsp + to spread; Onion|1 small; Capsicum|¼ each green, red and yellow; Cherry tomatoes|8-10; Veg mayonnaise|to spread; Oregano|¼ tsp; Black pepper|crushed, to taste; Pine nuts|12-15; Basil|4-5 leaves; Arugula|a handful; Salt|to taste',
    method: [
      'Butter one side of the bread and toast on a grill pan till golden on both sides.',
      'In a little butter, sauté the onion till translucent, add the chopped capsicums for a minute, then salt and the quartered cherry tomatoes for 2-3 minutes.',
      'Stir in the oregano, crushed pepper, pine nuts and torn basil.',
      'Spread mayo on the toast, pile on the vegetables and top with arugula. Serve straight away.',
    ],
  },
  // Egg dishes in the sample data (archived).
  'Masala Omelette': {
    from: 'description',
    ingredients: 'Eggs|2; Butter|1 tbsp; Onion|1 small; Green chilli|4; Tomato|1; Coriander leaves|1 tbsp + to garnish; Potato|2-3 medium, julienned; Oil|2½ tbsp; Cumin seeds|1 tsp; Ginger|1 inch; Garlic|2-3 cloves; Turmeric|½ tsp; Salt|to taste',
    method: [
      'Aloo bhujia: crackle cumin in oil, add ginger and garlic, then the potato juliennes with salt and turmeric; add green chilli, cover and cook till tender.',
      'Beat the eggs with coriander.',
      'In butter, sauté the onion and green chilli, add half the tomato, pour in the eggs and cook on medium, turning once.',
      'Salt the other tomato half and char it in a little oil till browned.',
      'Serve the omelette with the bhujia and tomato, garnished with coriander.',
    ],
  },
  'Shakshuka': {
    from: 'description',
    ingredients: 'Eggs|4; Ghee|1 tbsp; Onion|2 medium; Green chilli|2; Tomato|1 medium; Turmeric|¼ tsp; Kashmiri red chilli powder|1 tsp; Coriander powder|1 tsp; Garam masala|¼ tsp; Cream|2-3 tbsp; Black pepper|to taste; Bread|to serve; Salt|to taste',
    method: [
      'Finely chop the onion and chillies and fry in ghee on high till light golden, then lower the heat.',
      'Add the finely chopped tomato with salt and the spice powders; cook through, with a splash of hot water if needed.',
      'Stir in the cream briefly and check the salt.',
      'Spread the masala, make 4 wells, switch off the heat and slide an egg into each; season with salt and pepper.',
      'Cover and cook on the lowest heat for 3-4 minutes, till the whites set. Serve from the pan with bread.',
    ],
  },
};

const parse = (s) => s.split(';').map((x) => {
  const [name, qty = ''] = x.split('|').map((t) => t.trim());
  return { name, qty };
});

/** Ingredients (parsed), method and source for a dish, or null if we haven't checked its video yet. */
const BY_KEY = new Map(Object.entries(RECIPES).map(([name, r]) => [name.toLowerCase().trim(), r]));

export function recipeFor(name) {
  const r = BY_KEY.get(String(name || '').toLowerCase().trim());
  return r ? { ingredients: parse(r.ingredients), method: [...r.method], recipeFrom: r.from } : null;
}

// The ingredient names each catalogue dish had before these lists were checked against the videos.
// Saved data whose ingredients still match gets the video version; anything you've edited is left alone.
// Safe to delete once everyone has opened the app since this change.
export const LEGACY_INGREDIENTS = {
  'Palak Paneer': 'spinach,paneer,onion,tomato,ginger garlic paste,green chilli,cream,garam masala,cumin seeds',
  'Paneer Butter Masala': 'paneer,tomato,butter,cashews,cream,kasuri methi,ginger garlic paste,garam masala',
  'Matar Paneer': 'paneer,peas,onion,tomato,ginger garlic paste,garam masala',
  'Kadai Paneer': 'paneer,capsicum,onion,tomato,kadai masala,coriander leaves',
  'Paneer Bhurji': 'paneer,onion,tomato,capsicum,green chilli,coriander leaves',
  'Malai Kofta': 'paneer,potato,cashews,cream,tomato,onion,cornflour',
  'Dal Tadka': 'toor dal,onion,tomato,garlic,cumin seeds,ghee,red chilli powder,turmeric',
  'Dal Makhani': 'whole urad dal,rajma,butter,cream,tomato,ginger garlic paste',
  'Rajma Chawal': 'rajma,rice,onion,tomato,ginger garlic paste,garam masala',
  'Chole': 'kabuli chana,onion,tomato,chole masala,ginger garlic paste',
  'Kadhi Pakora': 'besan,curd,onion,curry leaves,fenugreek seeds,turmeric',
  'Aloo Gobi': 'potato,cauliflower,onion,tomato,turmeric,coriander leaves',
  'Aloo Matar': 'potato,peas,onion,tomato,cumin seeds,garam masala',
  'Baingan Bharta': 'brinjal,onion,tomato,garlic,green chilli,coriander leaves',
  'Mix Veg': 'mixed vegetables,onion,tomato,ginger garlic paste,garam masala',
  'Aloo Paratha': 'atta,potato,green chilli,coriander leaves,ghee,curd',
  'Besan Chilla': 'besan,onion,tomato,green chilli,coriander leaves',
  'Moong Dal Khichdi': 'moong dal,rice,ghee,cumin seeds,turmeric',
  'Jeera Rice': 'basmati rice,cumin seeds,ghee',
  'Veg Pulao': 'basmati rice,mixed vegetables,onion,whole garam masala,ghee',
  'Veg Biryani': 'basmati rice,mixed vegetables,curd,onion,biryani masala,saffron,mint leaves,ghee',
  'Pav Bhaji': 'pav,potato,cauliflower,peas,capsicum,tomato,onion,butter,pav bhaji masala,lemon',
  'Poha': 'poha,onion,peanuts,curry leaves,mustard seeds,turmeric,lemon,coriander leaves',
  'Methi Thepla': 'atta,methi leaves,curd,turmeric,red chilli powder',
  'Dhokla': 'besan,curd,eno,mustard seeds,curry leaves,green chilli',
  'Upma': 'rava,onion,curry leaves,mustard seeds,green chilli,peas',
  'Penne Arrabbiata': 'pasta,tomato,garlic,chilli flakes,olive oil,parmesan',
  'Pesto Pasta': 'pasta,basil,pine nuts,garlic,parmesan,olive oil',
  'Aglio e Olio': 'pasta,garlic,chilli flakes,olive oil,parsley',
  'Veg Lasagne': 'lasagne sheets,mixed vegetables,tomato,mozzarella,milk,butter,maida',
  'Minestrone Soup': 'mixed vegetables,pasta,rajma,tomato,garlic,veg stock',
  'Tomato Basil Soup': 'tomato,onion,garlic,basil,cream,butter',
  'Falafel & Hummus': 'kabuli chana,tahini,garlic,parsley,lemon,pita bread',
  'Veg Burrito Bowl': 'rice,rajma,corn,capsicum,tomato,onion,lemon,cheese',
  'Thai Green Curry': 'coconut milk,thai green curry paste,mixed vegetables,tofu,basil',
  'Veg Pad Thai': 'rice noodles,tofu,peanuts,tamarind,bean sprouts,soy sauce,lemon',
  'Tofu Stir-fry': 'tofu,broccoli,capsicum,garlic,soy sauce,cornflour,rice',
  'Veg Hakka Noodles': 'noodles,cabbage,carrot,capsicum,spring onion,soy sauce,vinegar',
  'Veg Fried Rice': 'rice,carrot,beans,spring onion,soy sauce,garlic',
  'Chilli Paneer': 'paneer,capsicum,onion,soy sauce,cornflour,green chilli,spring onion',
  'Veg Manchurian': 'cabbage,carrot,cornflour,maida,soy sauce,garlic,spring onion',
  'Masala Omelette': 'eggs,onion,tomato,green chilli,coriander leaves,bread',
  'Shakshuka': 'eggs,tomato,onion,capsicum,paprika',
};
