// Generated by scripts/build-shop-links.py from links/*.csv. Don't edit by hand; re-run the script.
// Amazon.in links. They carry an Amazon Associates tag, so the site shows a disclosure next to them.

export const INGREDIENT_LINKS = {
 "Ajwain": {
  "url": "https://www.amazon.in/dp/B0H1H6XH8Y?tag=tpr07-21",
  "product": "Tata Sampann Ajwain (Ajowan), 100g",
  "search": false
 },
 "Almonds": {
  "url": "https://www.amazon.in/dp/B09GNV7YZM?tag=tpr07-21",
  "product": "Tata Sampann Pure California Almonds/Badam Whole, 500g",
  "search": false
 },
 "Amchur": {
  "url": "https://www.amazon.in/dp/B0752S3195?tag=tpr07-21",
  "product": "Catch Amchur Powder, 100 g",
  "search": false
 },
 "Arborio rice": {
  "url": "https://www.amazon.in/dp/B09BNHLLHH?tag=tpr07-21",
  "product": "Abbie's Italian Arborio Rice, 1 kg",
  "search": false
 },
 "Aromat powder": {
  "url": "https://www.amazon.in/dp/B0GN3GKHB9?tag=tpr07-21",
  "product": "Knorr Aromat Seasoning Powder, 1kg",
  "search": false,
  "note": "niche item, only a 1 kg pack found; unlikely on Amazon Now"
 },
 "Atta": {
  "url": "https://www.amazon.in/dp/B007GGTLEC?tag=tpr07-21",
  "product": "Aashirvaad Shudh Chakki Atta, 5kg",
  "search": false
 },
 "Avocado": {
  "url": "https://www.amazon.in/dp/B07L8H6L2R?tag=tpr07-21",
  "product": "Fresh Avocado Regular, 1 Pc (Approx.150-200g)",
  "search": false
 },
 "Baby corn": {
  "url": "https://www.amazon.in/dp/B07BG6X1S1?tag=tpr07-21",
  "product": "Fresh Baby Corn, 200g",
  "search": false
 },
 "Baking soda": {
  "url": "https://www.amazon.in/dp/B09G96K43Z?tag=tpr07-21",
  "product": "Weikfield Baking Soda",
  "search": false
 },
 "Basil": {
  "url": "https://www.amazon.in/dp/B09NKXT8LM?tag=tpr07-21",
  "product": "Keya Basil, Freeze Dried",
  "search": false,
  "note": "fresh basil not listed; freeze-dried is the closest"
 },
 "Basmati rice": {
  "url": "https://www.amazon.in/dp/B0BBF1FT93?tag=tpr07-21",
  "product": "India Gate Basmati Rice Everyday 5 kg",
  "search": false
 },
 "Bay leaf": {
  "url": "https://www.amazon.in/dp/B08FCZC99Y?tag=tpr07-21",
  "product": "Chukde Bay Leaf (Tej Patta) 50gms",
  "search": false
 },
 "Bean sprouts": {
  "url": "https://www.amazon.in/dp/B077X8MD39?tag=tpr07-21",
  "product": "Tata Sampann Unpolished Green Moong Dal (Whole), 500 g",
  "search": false,
  "note": "ready sprouts not listed; sprout the moong at home"
 },
 "Beans": {
  "url": "https://www.amazon.in/dp/B07BG8JPXY?tag=tpr07-21",
  "product": "Fresh Beans French, 250g",
  "search": false
 },
 "Beetroot": {
  "url": "https://www.amazon.in/dp/B07BG7B7QP?tag=tpr07-21",
  "product": "Fresh Beet Root, 500g",
  "search": false
 },
 "Besan": {
  "url": "https://www.amazon.in/dp/B0752S522F?tag=tpr07-21",
  "product": "Tata Sampann 100% Chana Dal Fine Besan, 500g",
  "search": false
 },
 "Bhindi": {
  "url": "https://www.amazon.in/dp/B09WGXJ8PQ?tag=tpr07-21",
  "product": "Fresh Bhindi (Lady finger), 250g",
  "search": false
 },
 "Biryani masala": {
  "url": "https://www.amazon.in/dp/B019RL0PPW?tag=tpr07-21",
  "product": "Everest Shahi Biryani Masala, 50g",
  "search": false
 },
 "Black cardamom": {
  "url": "https://www.amazon.in/dp/B07H2TFK5Q?tag=tpr07-21",
  "product": "Amazon Brand - Vedaka Black Cardamom Whole (Moti Elaichi)",
  "search": false
 },
 "Black pepper": {
  "url": "https://www.amazon.in/dp/B0D8FBDJ4G?tag=tpr07-21",
  "product": "Catch Black Pepper Powder, 100 g",
  "search": false
 },
 "Black peppercorns": {
  "url": "https://www.amazon.in/dp/B0FDL8BW9J?tag=tpr07-21",
  "product": "Tata Sampann Black Pepper Whole, 100g",
  "search": false
 },
 "Black salt": {
  "url": "https://www.amazon.in/dp/B00H41JFCW?tag=tpr07-21",
  "product": "Catch Sprinkles Black Salt, 200g",
  "search": false
 },
 "Bread": {
  "url": "https://www.amazon.in/dp/B077Y832Z6?tag=tpr07-21",
  "product": "English Oven Premium White Bread, 350 g",
  "search": false
 },
 "Bread crumbs": {
  "url": "https://www.amazon.in/dp/B0GMWG8QQM?tag=tpr07-21",
  "product": "Abbie's Bread Crumbs, Japanese Style, 200 g",
  "search": false
 },
 "Brinjal": {
  "url": "https://www.amazon.in/dp/B07KK83WLB?tag=tpr07-21",
  "product": "Fresh Brinjal Nagpur (Gulabi), 500 g",
  "search": false,
  "note": "large bharta brinjal not listed"
 },
 "Broccoli": {
  "url": "https://www.amazon.in/dp/B09RGN6CW9?tag=tpr07-21",
  "product": "Fresh Broccoli, 1 pc (approx. 250-300g)",
  "search": false
 },
 "Brown sugar": {
  "url": "https://www.amazon.in/dp/B0F5PTCKYJ?tag=tpr07-21",
  "product": "Dhampure Mineral Brown Sugar, 1 kg",
  "search": false
 },
 "Butter": {
  "url": "https://www.amazon.in/dp/B01IBTCZNG?tag=tpr07-21",
  "product": "Amul Table Butter Salted, 100 g",
  "search": false
 },
 "Cabbage": {
  "url": "https://www.amazon.in/dp/B07BG521JL?tag=tpr07-21",
  "product": "Fresh Cabbage, 1 Pc (450g-750g)",
  "search": false
 },
 "Capsicum": {
  "url": "https://www.amazon.in/dp/B07BG51WMX?tag=tpr07-21",
  "product": "Fresh Capsicum - Green, 500g",
  "search": false
 },
 "Cardamom powder": {
  "url": "https://www.amazon.in/dp/B0G6VL281X?tag=tpr07-21",
  "product": "Snapin Cardamom Powder, 8 g pouch",
  "search": false
 },
 "Carrot": {
  "url": "https://www.amazon.in/s?k=fresh+carrot&tag=tpr07-21",
  "product": "Amazon search: fresh carrot",
  "search": true,
  "note": "no Amazon fresh carrot listing found; tagged search link"
 },
 "Cashews": {
  "url": "https://www.amazon.in/dp/B09GNSDZVW?tag=tpr07-21",
  "product": "Tata Sampann Pure Cashews Whole/Kaju, 500g",
  "search": false
 },
 "Cauliflower": {
  "url": "https://www.amazon.in/s?k=fresh+cauliflower&tag=tpr07-21",
  "product": "Amazon search: fresh cauliflower",
  "search": true,
  "note": "no Amazon fresh cauliflower listing found; tagged search link"
 },
 "Celery": {
  "url": "https://www.amazon.in/dp/B07BG4XKJ5?tag=tpr07-21",
  "product": "Fresh Celery, 500g",
  "search": false
 },
 "Chana dal": {
  "url": "https://www.amazon.in/dp/B0BSNQFBH4?tag=tpr07-21",
  "product": "Fortune Chana Dal, 1 kg",
  "search": false
 },
 "Cheese": {
  "url": "https://www.amazon.in/dp/B01FMCJDDA?tag=tpr07-21",
  "product": "Amul Cheese Block, 200 g",
  "search": false
 },
 "Chilli flakes": {
  "url": "https://www.amazon.in/dp/B00LN86ZIY?tag=tpr07-21",
  "product": "Keya Red Chilli Flakes",
  "search": false
 },
 "Chinese chives": {
  "url": "https://www.amazon.in/dp/B07NXZWD25?tag=tpr07-21",
  "product": "Fresh Spring Onion, 250 g",
  "search": false,
  "note": "fresh Chinese chives not listed; spring onion greens are the usual swap; not shown in Amazon search, so left out of dish bundles"
 },
 "Chole masala": {
  "url": "https://www.amazon.in/dp/B008ZEFY72?tag=tpr07-21",
  "product": "Everest Chhole Masala, 100g",
  "search": false
 },
 "Cinnamon": {
  "url": "https://www.amazon.in/dp/B01IENENPC?tag=tpr07-21",
  "product": "Organic Tattva Cinnamon Sticks, 50g",
  "search": false
 },
 "Cloves": {
  "url": "https://www.amazon.in/dp/B0FDL91HVS?tag=tpr07-21",
  "product": "Tata Sampann Clove Whole, 50g",
  "search": false
 },
 "Coarse red chilli powder": {
  "url": "https://www.amazon.in/dp/B08K7C6C8X?tag=tpr07-21",
  "product": "Marwar Kuti Lal Mirch (coarse ground red chilli)",
  "search": false
 },
 "Coconut": {
  "url": "https://www.amazon.in/dp/B07BG7D7WR?tag=tpr07-21",
  "product": "Fresh Coconut - Medium 1 Pc (400-450g)",
  "search": false
 },
 "Coconut milk": {
  "url": "https://www.amazon.in/dp/B015QZI2LC?tag=tpr07-21",
  "product": "Dabur Hommade Coconut Milk",
  "search": false
 },
 "Coriander leaves": {
  "url": "https://www.amazon.in/dp/B07BG5GJJW?tag=tpr07-21",
  "product": "Fresh Coriander Leaves, 100 g",
  "search": false
 },
 "Coriander powder": {
  "url": "https://www.amazon.in/dp/B00LIO5JYE?tag=tpr07-21",
  "product": "Catch Coriander Powder, 100g",
  "search": false
 },
 "Coriander seeds": {
  "url": "https://www.amazon.in/dp/B0DJ96LS3S?tag=tpr07-21",
  "product": "Tata Sampann Coriander Whole (Dhaniya)",
  "search": false
 },
 "Corn": {
  "url": "https://www.amazon.in/dp/B0CB7YYH42?tag=tpr07-21",
  "product": "Pluckk Sweet Corn, 2 Pc",
  "search": false
 },
 "Cornflour": {
  "url": "https://www.amazon.in/dp/B075335G7V?tag=tpr07-21",
  "product": "Weikfield Corn Starch Powder, 100g",
  "search": false
 },
 "Cream": {
  "url": "https://www.amazon.in/dp/B077RK8L9N?tag=tpr07-21",
  "product": "Mother Dairy Cream, 200ml",
  "search": false
 },
 "Cucumber": {
  "url": "https://www.amazon.in/dp/B07BG7B7WB?tag=tpr07-21",
  "product": "Fresh Cucumber, 500g",
  "search": false
 },
 "Cumin powder": {
  "url": "https://www.amazon.in/dp/B0154VT0GY?tag=tpr07-21",
  "product": "Catch Jeera (Cumin) Powder, 100g",
  "search": false
 },
 "Cumin seeds": {
  "url": "https://www.amazon.in/dp/B0DJ97QP87?tag=tpr07-21",
  "product": "Tata Sampann Cumin Seed (Jeera), Whole",
  "search": false
 },
 "Curd": {
  "url": "https://www.amazon.in/dp/B077RFB9TN?tag=tpr07-21",
  "product": "Mother Dairy Classic Curd Pouch, 1000 g",
  "search": false
 },
 "Curry leaves": {
  "url": "https://www.amazon.in/dp/B07BG6WKLS?tag=tpr07-21",
  "product": "Fresh Curry Leaves, 100 grams Bunch",
  "search": false
 },
 "Degi red chilli powder": {
  "url": "https://www.amazon.in/dp/B003P8N772?tag=tpr07-21",
  "product": "MDH Deggi Chilli Powder, 100 g",
  "search": false
 },
 "Dosa batter": {
  "url": "https://www.amazon.in/dp/B01468O5AW?tag=tpr07-21",
  "product": "iD Fresh Idly and Dosa Batter, 1 Kg Pouch",
  "search": false
 },
 "Dried amla": {
  "url": "https://www.amazon.in/dp/B0H94MZQRX?tag=tpr07-21",
  "product": "House of Nuts N Spices Dry Amla Whole Pieces, 250g",
  "search": false,
  "note": "niche item; unlikely on Amazon Now"
 },
 "Drumstick": {
  "url": "https://www.amazon.in/dp/B07BG523CL?tag=tpr07-21",
  "product": "Fresh Drumstick (Moringa), 250g Cut",
  "search": false
 },
 "Dry fruits": {
  "url": "https://www.amazon.in/dp/B09MM96YC4?tag=tpr07-21",
  "product": "Farmley Panchmeva Dry Fruits Mix, 425g",
  "search": false
 },
 "Dry red chilli (Kashmiri)": {
  "url": "https://www.amazon.in/dp/B0D5VHYDHN?tag=tpr07-21",
  "product": "Khetika Naturale Kashmiri Chilli Whole, 100 g",
  "search": false
 },
 "Eggs": {
  "url": "https://www.amazon.in/dp/B0DG5PG3CX?tag=tpr07-21",
  "product": "Fresh White Eggs, 6 Piece",
  "search": false
 },
 "Fenugreek seeds": {
  "url": "https://www.amazon.in/dp/B0D56VRX5C?tag=tpr07-21",
  "product": "Khetika Whole Methi Dana, 200g",
  "search": false
 },
 "Feta": {
  "url": "https://www.amazon.in/dp/B089F2PTFK?tag=tpr07-21",
  "product": "Amul Feta Cheese, 250 g",
  "search": false
 },
 "Fried onions": {
  "url": "https://www.amazon.in/dp/B07FFCGD8F?tag=tpr07-21",
  "product": "Desire Golden Fried Onion (Birista), 250 g",
  "search": false
 },
 "Fried tofu": {
  "url": "https://www.amazon.in/dp/B09PKCK86L?tag=tpr07-21",
  "product": "Soyarich Tofu Premium, 200 g",
  "search": false,
  "note": "plain tofu; fry at home (ready-fried tofu not found)"
 },
 "Garam masala": {
  "url": "https://www.amazon.in/dp/B017BK7MD4?tag=tpr07-21",
  "product": "Everest Garam Masala, 50g",
  "search": false
 },
 "Garlic": {
  "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21",
  "product": "Amazon search: fresh garlic",
  "search": true,
  "note": "no Amazon fresh garlic listing found; tagged search link"
 },
 "Garlic paste": {
  "url": "https://www.amazon.in/dp/B00TZS18QS?tag=tpr07-21",
  "product": "Dabur Hommade Garlic Paste, 200 g",
  "search": false
 },
 "Garlic powder": {
  "url": "https://www.amazon.in/dp/B09BYSKVD6?tag=tpr07-21",
  "product": "Snapin Garlic Powder, 50 g",
  "search": false
 },
 "Ghee": {
  "url": "https://www.amazon.in/dp/B09WMPCGVP?tag=tpr07-21",
  "product": "Amul Cow Ghee, 1 Litre Tetra Pack",
  "search": false
 },
 "Ginger": {
  "url": "https://www.amazon.in/dp/B07BG7B7RF?tag=tpr07-21",
  "product": "Fresh Ginger (Adrak), 100g",
  "search": false
 },
 "Ginger garlic paste": {
  "url": "https://www.amazon.in/dp/B083QDBBBW?tag=tpr07-21",
  "product": "Catch Ginger Garlic Paste, 200 g",
  "search": false
 },
 "Ginger paste": {
  "url": "https://www.amazon.in/dp/B00TZS1CFA?tag=tpr07-21",
  "product": "Dabur Hommade Ginger Paste, 200 g",
  "search": false
 },
 "Green cardamom": {
  "url": "https://www.amazon.in/dp/B0CJK23XJQ?tag=tpr07-21",
  "product": "Zoff Green Cardamom Whole (Choti Elaichi)",
  "search": false
 },
 "Green chilli": {
  "url": "https://www.amazon.in/dp/B07BG7LB5B?tag=tpr07-21",
  "product": "Fresh Chilli - Green, 100g",
  "search": false
 },
 "Green chilli paste": {
  "url": "https://www.amazon.in/dp/B07BG7LB5B?tag=tpr07-21",
  "product": "Fresh Chilli - Green, 100g",
  "search": false,
  "note": "no mainstream green chilli paste found; grind fresh green chillies"
 },
 "Hing": {
  "url": "https://www.amazon.in/dp/B0BBGB4RMH?tag=tpr07-21",
  "product": "Tata Sampann Hing, Compounded Asafoetida (Bandhani Hing), 50g",
  "search": false
 },
 "Honey": {
  "url": "https://www.amazon.in/dp/B07J57J784?tag=tpr07-21",
  "product": "Dabur Honey, 450g (225g x 2)",
  "search": false
 },
 "Idli batter": {
  "url": "https://www.amazon.in/dp/B01468O5AW?tag=tpr07-21",
  "product": "iD Fresh Idly and Dosa Batter, 1 Kg Pouch",
  "search": false
 },
 "Jalapeño": {
  "url": "https://www.amazon.in/dp/B09GYK1DHQ?tag=tpr07-21",
  "product": "Neo Sliced Jalapenos, 350g",
  "search": false
 },
 "Japanese curry cubes": {
  "url": "https://www.amazon.in/dp/B07BRMLY3C?tag=tpr07-21",
  "product": "S&B Golden Curry Sauce Mix (Japanese Curry Roux), Medium Hot",
  "search": false,
  "note": "imported item; unlikely on Amazon Now"
 },
 "Kabuli chana": {
  "url": "https://www.amazon.in/dp/B0BRJ2RBMY?tag=tpr07-21",
  "product": "Tata Sampann Unpolished Kabuli Chana, 1 kg",
  "search": false
 },
 "Kadai masala": {
  "url": "https://www.amazon.in/dp/B09BD6WDH2?tag=tpr07-21",
  "product": "Suhana Kadai Paneer Spice Mix, 50g (Pack of 5)",
  "search": false
 },
 "Kaffir lime leaves": {
  "url": "https://www.amazon.in/dp/B0BSR149NL?tag=tpr07-21",
  "product": "Nourcery Dried Kaffir Lime Leaves, 15 g",
  "search": false,
  "note": "dried; fresh leaves not found"
 },
 "Kashmiri red chilli powder": {
  "url": "https://www.amazon.in/dp/B01B7DZ79M?tag=tpr07-21",
  "product": "Catch Kashmiri Chilli Powder, 100 g",
  "search": false
 },
 "Kasuri methi": {
  "url": "https://www.amazon.in/dp/B08H64PTLG?tag=tpr07-21",
  "product": "Tata Sampann Kasuri Methi, 25 g",
  "search": false
 },
 "Kewra water": {
  "url": "https://www.amazon.in/dp/B00JEWEUFG?tag=tpr07-21",
  "product": "Dabur Keora Water, 250ml",
  "search": false
 },
 "Lasagne sheets": {
  "url": "https://www.amazon.in/dp/B0BWNRBL5X?tag=tpr07-21",
  "product": "Gustora Lasagne Sheets",
  "search": false
 },
 "Lemon": {
  "url": "https://www.amazon.in/dp/B0DFLR6C1V?tag=tpr07-21",
  "product": "Fresh Lemon Seedless Premium, 2 Pc",
  "search": false
 },
 "Lettuce": {
  "url": "https://www.amazon.in/dp/B07BG79ZD6?tag=tpr07-21",
  "product": "Fresh Lettuce, Green 1 Pc",
  "search": false
 },
 "Lime": {
  "url": "https://www.amazon.in/dp/B0DFLR6C1V?tag=tpr07-21",
  "product": "Fresh Lemon Seedless Premium, 2 Pc",
  "search": false,
  "note": "no separate lime listing; Indian lemons (nimbu) work as lime"
 },
 "Mace": {
  "url": "https://www.amazon.in/dp/B0CBVMFYL9?tag=tpr07-21",
  "product": "Chukde Mace (Javitri), 25 g",
  "search": false
 },
 "Maida": {
  "url": "https://www.amazon.in/dp/B08DRSJGCD?tag=tpr07-21",
  "product": "Fortune Maida Pouch, 500 g",
  "search": false
 },
 "Maple syrup": {
  "url": "https://www.amazon.in/dp/B00B5SLEN8?tag=tpr07-21",
  "product": "Maple Joe Canadian Grade A Maple Syrup, 250g",
  "search": false
 },
 "Mawa": {
  "url": "https://www.amazon.in/dp/B0HJM7PG3H?tag=tpr07-21",
  "product": "Nutra Vita Freeze Dried Khoya (Mawa), 110 g",
  "search": false,
  "note": "fresh khoya not listed; unlikely on Amazon Now"
 },
 "Methi leaves": {
  "url": "https://www.amazon.in/dp/B07BG7LB95?tag=tpr07-21",
  "product": "Fresh Methi, 250g Pack",
  "search": false
 },
 "Milk": {
  "url": "https://www.amazon.in/dp/B01IA43GSU?tag=tpr07-21",
  "product": "Mother Dairy Milk - Full Cream, 500ml Pack",
  "search": false
 },
 "Mint leaves": {
  "url": "https://www.amazon.in/dp/B07BG65QL5?tag=tpr07-21",
  "product": "Fresh Mint Leaves, 100 grams",
  "search": false
 },
 "Mixed vegetables": {
  "url": "https://www.amazon.in/s?k=frozen+mixed+vegetables&tag=tpr07-21",
  "product": "Amazon search: frozen mixed vegetables",
  "search": true,
  "note": "no frozen mixed vegetables listing found; tagged search link"
 },
 "Moong dal": {
  "url": "https://www.amazon.in/dp/B075332XK6?tag=tpr07-21",
  "product": "Tata Sampann Unpolished Moong Dal (Split), 500 g",
  "search": false
 },
 "Mozzarella": {
  "url": "https://www.amazon.in/dp/B0BHLD142Z?tag=tpr07-21",
  "product": "D'lecta 100% Mozzarella Cheese Block, 200g",
  "search": false
 },
 "Mushroom": {
  "url": "https://www.amazon.in/dp/B07BG79Z9M?tag=tpr07-21",
  "product": "Fresh Mushroom (Approx. 180-200g)",
  "search": false
 },
 "Mustard oil": {
  "url": "https://www.amazon.in/dp/B01ABRU2JA?tag=tpr07-21",
  "product": "Fortune Kachi Ghani Mustard Oil, 500ml",
  "search": false
 },
 "Mustard seeds": {
  "url": "https://www.amazon.in/dp/B0FDL9B3B8?tag=tpr07-21",
  "product": "Tata Sampann Mustard Whole, 200g",
  "search": false
 },
 "Noodles": {
  "url": "https://www.amazon.in/dp/B00FHD9Y5W?tag=tpr07-21",
  "product": "Ching's Veg Hakka Noodles",
  "search": false
 },
 "Nutmeg": {
  "url": "https://www.amazon.in/dp/B08XVX7WFX?tag=tpr07-21",
  "product": "Snapin Nutmeg Powder (Jaiphal), 50 g",
  "search": false
 },
 "Oil": {
  "url": "https://www.amazon.in/dp/B0GDQWH88W?tag=tpr07-21",
  "product": "Fortune Sunlite Refined Sunflower Oil, 1L Pouch",
  "search": false
 },
 "Olive oil": {
  "url": "https://www.amazon.in/dp/B00X7RJSW4?tag=tpr07-21",
  "product": "Figaro Extra Virgin Olive Oil",
  "search": false
 },
 "Olives": {
  "url": "https://www.amazon.in/dp/B01MTB4BR7?tag=tpr07-21",
  "product": "Del Monte Black Sliced Olives, 235g",
  "search": false
 },
 "Onion": {
  "url": "https://www.amazon.in/dp/B07HN2W64R?tag=tpr07-21",
  "product": "Fresh Onion, 500 gm",
  "search": false
 },
 "Onion powder": {
  "url": "https://www.amazon.in/dp/B09BYLN5YW?tag=tpr07-21",
  "product": "Snapin White Onion Powder, 40g",
  "search": false
 },
 "Onion rings": {
  "url": "https://www.amazon.in/dp/B07HN2W64R?tag=tpr07-21",
  "product": "Fresh Onion, 500 gm",
  "search": false,
  "note": "raw onion sliced into rings as garnish"
 },
 "Oregano": {
  "url": "https://www.amazon.in/dp/B01GJIGZIM?tag=tpr07-21",
  "product": "Keya Italian Pizza Oregano",
  "search": false
 },
 "Paneer": {
  "url": "https://www.amazon.in/dp/B078KT9RB1?tag=tpr07-21",
  "product": "Amul Fresh Malai Paneer Block Pouch, 200 g",
  "search": false
 },
 "Parmesan": {
  "url": "https://www.amazon.in/dp/B0G4X199DK?tag=tpr07-21",
  "product": "Old Hill Parmesan Cheese, 100g",
  "search": false
 },
 "Parsley": {
  "url": "https://www.amazon.in/dp/B0DPCCQXNN?tag=tpr07-21",
  "product": "Fresh Parsley, 50 g",
  "search": false,
  "note": "not shown in Amazon search, so left out of dish bundles"
 },
 "Pasta": {
  "url": "https://www.amazon.in/dp/B0GX1YYY8R?tag=tpr07-21",
  "product": "DiSano Penne Pasta, 400g (Pack of 2)",
  "search": false
 },
 "Pav": {
  "url": "https://www.amazon.in/dp/B0D2LJQCBP?tag=tpr07-21",
  "product": "Britannia Bombay Pav, 250 g (6 pcs)",
  "search": false
 },
 "Pav bhaji masala": {
  "url": "https://www.amazon.in/dp/B0154VTRB2?tag=tpr07-21",
  "product": "Everest Pav Bhaji Masala, 50g",
  "search": false
 },
 "Peanuts": {
  "url": "https://www.amazon.in/dp/B0FF4VVGS4?tag=tpr07-21",
  "product": "Khetika Peanuts, 1 kg",
  "search": false
 },
 "Peas": {
  "url": "https://www.amazon.in/dp/B0FF9Z6D5D?tag=tpr07-21",
  "product": "Pluckk Green Peas Shelled",
  "search": false
 },
 "Pita bread": {
  "url": "https://www.amazon.in/s?k=pita+bread&tag=tpr07-21",
  "product": "Amazon search: pita bread",
  "search": true,
  "note": "only pita chips found; tagged search link"
 },
 "Pizza base": {
  "url": "https://www.amazon.in/dp/B0DG5KRNW5?tag=tpr07-21",
  "product": "Bonn Pizza Base, 200g",
  "search": false
 },
 "Pizza sauce": {
  "url": "https://www.amazon.in/dp/B00O8X0GI6?tag=tpr07-21",
  "product": "Del Monte Pizza and Pasta Sauce, 400 g",
  "search": false
 },
 "Pizza seasoning": {
  "url": "https://www.amazon.in/dp/B00KPSQW04?tag=tpr07-21",
  "product": "Keya Pizza Seasoning, 45 g",
  "search": false
 },
 "Poha": {
  "url": "https://www.amazon.in/dp/B09PDZYN2X?tag=tpr07-21",
  "product": "Fortune Thick Poha, 500 g",
  "search": false
 },
 "Potato": {
  "url": "https://www.amazon.in/dp/B07BG5GZP2?tag=tpr07-21",
  "product": "Fresh Potato, 1kg",
  "search": false
 },
 "Processed cheese": {
  "url": "https://www.amazon.in/dp/B01FMCJDDA?tag=tpr07-21",
  "product": "Amul Cheese Block (processed), 200 g",
  "search": false
 },
 "Rajma": {
  "url": "https://www.amazon.in/dp/B0CP3KK885?tag=tpr07-21",
  "product": "Tata Sampann Unpolished Red Rajma, 500g",
  "search": false
 },
 "Rava": {
  "url": "https://www.amazon.in/dp/B08DRPYQT3?tag=tpr07-21",
  "product": "Fortune Suji Pouch, 500 g",
  "search": false
 },
 "Red chilli": {
  "url": "https://www.amazon.in/dp/B0H1H7PWYK?tag=tpr07-21",
  "product": "Tata Sampann Red Chilli Whole, 100g",
  "search": false,
  "note": "fresh red chilli not listed; dried whole red chilli"
 },
 "Red chilli powder": {
  "url": "https://www.amazon.in/dp/B01B7DZ8BE?tag=tpr07-21",
  "product": "Catch Red Chilli Powder, 100g",
  "search": false
 },
 "Red chilli sauce": {
  "url": "https://www.amazon.in/dp/B09H6KZYJ9?tag=tpr07-21",
  "product": "Ching's Secret Red Chilli Sauce, 200g",
  "search": false
 },
 "Red onion": {
  "url": "https://www.amazon.in/dp/B07HN2W64R?tag=tpr07-21",
  "product": "Fresh Onion, 500 gm",
  "search": false,
  "note": "no separate red onion listing; Indian onions are red onions"
 },
 "Rice": {
  "url": "https://www.amazon.in/dp/B00YGMLWQO?tag=tpr07-21",
  "product": "Fortune Rozana Gold Basmati Rice, 1 Kg",
  "search": false
 },
 "Rice noodles": {
  "url": "https://www.amazon.in/dp/B0FZVWJBHR?tag=tpr07-21",
  "product": "MasterChow Rice Noodles",
  "search": false
 },
 "Roasted cumin powder": {
  "url": "https://www.amazon.in/dp/B08J7QJD3T?tag=tpr07-21",
  "product": "PCM Roasted Jeera Powder, 100g",
  "search": false
 },
 "Salt": {
  "url": "https://www.amazon.in/dp/B07575FPC3?tag=tpr07-21",
  "product": "Tata Salt, 1 Kg",
  "search": false
 },
 "Sambar masala": {
  "url": "https://www.amazon.in/dp/B009LL92VC?tag=tpr07-21",
  "product": "MTR Sambar Powder",
  "search": false
 },
 "Sesame seeds": {
  "url": "https://www.amazon.in/dp/B0C289FV4B?tag=tpr07-21",
  "product": "True Elements White Sesame Seeds, 150 g",
  "search": false
 },
 "Sev": {
  "url": "https://www.amazon.in/dp/B00LP2LWPY?tag=tpr07-21",
  "product": "Haldiram's Long Sev",
  "search": false
 },
 "Shahi jeera": {
  "url": "https://www.amazon.in/dp/B0FBM7XTJH?tag=tpr07-21",
  "product": "Thakar Shahi Jeera (Black Cumin / Caraway)",
  "search": false,
  "note": "niche item; unlikely on Amazon Now"
 },
 "Soy sauce": {
  "url": "https://www.amazon.in/dp/B09H6KX7SW?tag=tpr07-21",
  "product": "Ching's Secret Dark Soy Sauce, 210g",
  "search": false
 },
 "Spinach": {
  "url": "https://www.amazon.in/dp/B07BG68KXT?tag=tpr07-21",
  "product": "Fresh Spinach, 250g",
  "search": false
 },
 "Spring onion": {
  "url": "https://www.amazon.in/dp/B07NXZWD25?tag=tpr07-21",
  "product": "Fresh Spring Onion, 250 g",
  "search": false,
  "note": "not shown in Amazon search, so left out of dish bundles"
 },
 "Sugar": {
  "url": "https://www.amazon.in/dp/B08WZQ1SN3?tag=tpr07-21",
  "product": "Fortune Sugar, 1 kg",
  "search": false
 },
 "Sweet corn": {
  "url": "https://www.amazon.in/dp/B0CYT9FJVQ?tag=tpr07-21",
  "product": "Neo Sweet Corn Kernels, 420g Tin",
  "search": false
 },
 "Tabasco": {
  "url": "https://www.amazon.in/dp/B00LXSDTTC?tag=tpr07-21",
  "product": "Tabasco Pepper Sauce, 60 ml",
  "search": false
 },
 "Tahini": {
  "url": "https://www.amazon.in/dp/B0C431CK5Y?tag=tpr07-21",
  "product": "5:15PM Tahini Paste, 300 g",
  "search": false
 },
 "Tamarind": {
  "url": "https://www.amazon.in/dp/B0D5VCPPNW?tag=tpr07-21",
  "product": "Khetika Tamarind Seedless, 200 g",
  "search": false
 },
 "Tamarind paste": {
  "url": "https://www.amazon.in/dp/B015QZI2NK?tag=tpr07-21",
  "product": "Dabur Hommade Tamarind Paste, 200 g",
  "search": false
 },
 "Tartaric acid": {
  "url": "https://www.amazon.in/dp/B0994VRWWW?tag=tpr07-21",
  "product": "Yuvika Tartaric Acid (Tatri), 100 g",
  "search": false
 },
 "Tea leaves": {
  "url": "https://www.amazon.in/dp/B00AP7YFFY?tag=tpr07-21",
  "product": "Tata Tea Agni",
  "search": false
 },
 "Thai basil": {
  "url": "https://www.amazon.in/dp/B09NKXT8LM?tag=tpr07-21",
  "product": "Keya Basil, Freeze Dried",
  "search": false,
  "note": "Thai basil not listed; regular basil is the closest"
 },
 "Thai green curry paste": {
  "url": "https://www.amazon.in/dp/B081L16JTJ?tag=tpr07-21",
  "product": "Real Thai Green Curry Paste, 227 g",
  "search": false
 },
 "Tofu": {
  "url": "https://www.amazon.in/dp/B09PKCK86L?tag=tpr07-21",
  "product": "Soyarich Tofu Premium, 200 g",
  "search": false
 },
 "Tomato": {
  "url": "https://www.amazon.in/dp/B08JQTG681?tag=tpr07-21",
  "product": "Naturally Grown Tomato, 1 Kg",
  "search": false,
  "note": "the listing you sent"
 },
 "Tomato ketchup": {
  "url": "https://www.amazon.in/dp/B09C3STJ24?tag=tpr07-21",
  "product": "Kissan Fresh Tomato Ketchup Pouch, 1.1 Kg",
  "search": false
 },
 "Tomato purée": {
  "url": "https://www.amazon.in/dp/B00N8KOJ88?tag=tpr07-21",
  "product": "Dabur Hommade Tomato Puree",
  "search": false
 },
 "Toor dal": {
  "url": "https://www.amazon.in/dp/B074N7VHV4?tag=tpr07-21",
  "product": "Tata Sampann Unpolished Toor Dal/Arhar Dal, 1kg",
  "search": false
 },
 "Tortillas": {
  "url": "https://www.amazon.in/dp/B07S8J2K32?tag=tpr07-21",
  "product": "Habanero Tortilla Wraps, 8 inch",
  "search": false
 },
 "Turmeric": {
  "url": "https://www.amazon.in/dp/B079H8D8M6?tag=tpr07-21",
  "product": "Tata Sampann Turmeric Powder, 200g",
  "search": false
 },
 "Urad dal": {
  "url": "https://www.amazon.in/dp/B077X8RBG1?tag=tpr07-21",
  "product": "Tata Sampann Unpolished Urad Dal (Split), 500 g",
  "search": false
 },
 "Veg stock": {
  "url": "https://www.amazon.in/dp/B005LLZ2GK?tag=tpr07-21",
  "product": "Knorr Vegetable Stock Cubes, 80 g",
  "search": false
 },
 "Vinegar": {
  "url": "https://www.amazon.in/dp/B0C5N1PYZB?tag=tpr07-21",
  "product": "Tops White Vinegar, 610 g",
  "search": false
 },
 "Walnuts": {
  "url": "https://www.amazon.in/dp/B0C65WVW3W?tag=tpr07-21",
  "product": "Tata Sampann Premium Walnut Kernels, 200g",
  "search": false
 },
 "White pepper powder": {
  "url": "https://www.amazon.in/dp/B00O0X7B3M?tag=tpr07-21",
  "product": "Everest White Pepper Powder, 100 g",
  "search": false
 },
 "Whole garam masala": {
  "url": "https://www.amazon.in/dp/B0DF7F726R?tag=tpr07-21",
  "product": "Nutraj Garam Masala Whole, 100 g",
  "search": false
 },
 "Whole urad dal": {
  "url": "https://www.amazon.in/dp/B077X9KLBZ?tag=tpr07-21",
  "product": "Tata Sampann Unpolished Urad Kali (Whole Black Urad), 500g",
  "search": false
 },
 "Zucchini": {
  "url": "https://www.amazon.in/dp/B0CGHR3KQM?tag=tpr07-21",
  "product": "Fresh Zucchini Green, Pack of 2 (approx. 300-400g)",
  "search": false
 }
};

export const DISH_BUNDLES = {
 "Palak Paneer": {
  "url": "https://www.amazon.in/s?k=B07BG68KXT%7CB07BG7B7RF%7CB07BG7LB5B%7CB09WMPCGVP%7CB0GDQWH88W%7CB0DJ97QP87%7CB0FDL91HVS%7CB08FCZC99Y%7CB0BBGB4RMH%7CB07HN2W64R%7CB08JQTG681%7CB0DJ96LS3S%7CB08H64PTLG%7CB079H8D8M6%7CB01B7DZ8BE%7CB078KT9RB1%7CB077RK8L9N%7CB017BK7MD4%7CB07575FPC3&tag=tpr07-21",
  "count": 19,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Paneer Butter Masala": {
  "url": "https://www.amazon.in/s?k=B078KT9RB1%7CB09WMPCGVP%7CB01IBTCZNG%7CB08FCZC99Y%7CB0CJK23XJQ%7CB0FDL91HVS%7CB07BG7B7RF%7CB07BG7LB5B%7CB07HN2W64R%7CB0D5VHYDHN%7CB09GNSDZVW%7CB08JQTG681%7CB003P8N772%7CB00LIO5JYE%7CB079H8D8M6%7CB077RFB9TN%7CB00JEWEUFG%7CB07J57J784%7CB08H64PTLG%7CB07BG5GJJW%7CB07575FPC3&tag=tpr07-21",
  "count": 21,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Matar Paneer": {
  "url": "https://www.amazon.in/s?k=B078KT9RB1%7CB0FF9Z6D5D%7CB08JQTG681%7CB07BG7LB5B%7CB07BG7B7RF%7CB0DJ97QP87%7CB0BBGB4RMH%7CB077RK8L9N%7CB079H8D8M6%7CB00LIO5JYE%7CB01B7DZ8BE%7CB017BK7MD4%7CB07BG5GJJW%7CB0GDQWH88W%7CB07575FPC3&tag=tpr07-21",
  "count": 15,
  "leftOut": []
 },
 "Kadai Paneer": {
  "url": "https://www.amazon.in/s?k=B0DJ96LS3S%7CB0DJ97QP87%7CB0D5VHYDHN%7CB0FDL8BW9J%7CB0GDQWH88W%7CB09WMPCGVP%7CB07BG7B7RF%7CB07HN2W64R%7CB083QDBBBW%7CB079H8D8M6%7CB003P8N772%7CB00LIO5JYE%7CB08JQTG681%7CB07BG51WMX%7CB078KT9RB1%7CB01B7DZ79M%7CB077RK8L9N%7CB07BG5GJJW%7CB07575FPC3&tag=tpr07-21",
  "count": 19,
  "leftOut": []
 },
 "Paneer Bhurji": {
  "url": "https://www.amazon.in/s?k=B078KT9RB1%7CB07HN2W64R%7CB08JQTG681%7CB07BG7B7RF%7CB07BG7LB5B%7CB079H8D8M6%7CB01B7DZ79M%7CB00LIO5JYE%7CB0154VT0GY%7CB0154VTRB2%7CB017BK7MD4%7CB0752S522F%7CB08H64PTLG%7CB01IBTCZNG%7CB0GDQWH88W%7CB07BG5GJJW%7CB07575FPC3&tag=tpr07-21",
  "count": 17,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Malai Kofta": {
  "url": "https://www.amazon.in/s?k=B07BG5GZP2%7CB078KT9RB1%7CB0HJM7PG3H%7CB0D8FBDJ4G%7CB07BG7B7RF%7CB09G96K43Z%7CB075335G7V%7CB0GDQWH88W%7CB09MM96YC4%7CB07BG5GJJW%7CB0G6VL281X%7CB09WMPCGVP%7CB08FCZC99Y%7CB0CJK23XJQ%7CB0FDL8BW9J%7CB0DJ97QP87%7CB07HN2W64R%7CB00LIO5JYE%7CB01B7DZ8BE%7CB079H8D8M6%7CB08JQTG681%7CB09GNSDZVW%7CB08H64PTLG%7CB077RK8L9N%7CB07575FPC3&tag=tpr07-21",
  "count": 25,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Dal Tadka": {
  "url": "https://www.amazon.in/s?k=B074N7VHV4%7CB075332XK6%7CB09WMPCGVP%7CB0GDQWH88W%7CB07BG7B7RF%7CB07BG7LB5B%7CB07HN2W64R%7CB0DJ97QP87%7CB079H8D8M6%7CB01B7DZ8BE%7CB0D5VHYDHN%7CB01B7DZ79M%7CB0BBGB4RMH%7CB07BG5GJJW%7CB07575FPC3&tag=tpr07-21",
  "count": 15,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Dal Makhani": {
  "url": "https://www.amazon.in/s?k=B077X9KLBZ%7CB0CP3KK885%7CB0BSNQFBH4%7CB09WMPCGVP%7CB01IBTCZNG%7CB07BG7B7RF%7CB07BG7LB5B%7CB0GDQWH88W%7CB003P8N772%7CB079H8D8M6%7CB00LIO5JYE%7CB0DJ97QP87%7CB0FDL8BW9J%7CB08H64PTLG%7CB0BBGB4RMH%7CB08JQTG681%7CB077RK8L9N%7CB07BG5GJJW%7CB07575FPC3&tag=tpr07-21",
  "count": 19,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Rajma Chawal": {
  "url": "https://www.amazon.in/s?k=B0CP3KK885%7CB0GDQWH88W%7CB08FCZC99Y%7CB07H2TFK5Q%7CB0DJ97QP87%7CB07HN2W64R%7CB07BG7LB5B%7CB00TZS1CFA%7CB00TZS18QS%7CB01B7DZ79M%7CB079H8D8M6%7CB00LIO5JYE%7CB08JQTG681%7CB08H64PTLG%7CB017BK7MD4%7CB09WMPCGVP%7CB07575FPC3%7CB00YGMLWQO&tag=tpr07-21",
  "count": 18,
  "leftOut": []
 },
 "Chole": {
  "url": "https://www.amazon.in/s?k=B0BRJ2RBMY%7CB0H94MZQRX%7CB00AP7YFFY%7CB09G96K43Z%7CB008ZEFY72%7CB0GDQWH88W%7CB0BBGB4RMH%7CB07BG7B7RF%7CB07BG7LB5B%7CB07HN2W64R%7CB079H8D8M6%7CB01B7DZ79M%7CB08JQTG681%7CB0D5VCPPNW%7CB00H41JFCW%7CB09WMPCGVP%7CB07575FPC3%7CB07BG5GZP2&tag=tpr07-21",
  "count": 18,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Kadhi Pakora": {
  "url": "https://www.amazon.in/s?k=B0752S522F%7CB077RFB9TN%7CB0GDQWH88W%7CB0DJ97QP87%7CB07BG7B7RF%7CB0D56VRX5C%7CB07BG7LB5B%7CB079H8D8M6%7CB08K7C6C8X%7CB0D5VHYDHN%7CB0BBGB4RMH%7CB07BG6WKLS%7CB01B7DZ79M%7CB07575FPC3&tag=tpr07-21",
  "count": 14,
  "leftOut": []
 },
 "Aloo Gobi": {
  "url": "https://www.amazon.in/s?k=B07BG5GZP2%7CB08JQTG681%7CB07BG7B7RF%7CB07BG7LB5B%7CB0GDQWH88W%7CB07BG5GJJW%7CB0DJ97QP87%7CB0BBGB4RMH%7CB079H8D8M6%7CB00LIO5JYE%7CB01B7DZ8BE%7CB08FCZC99Y%7CB01IENENPC%7CB0FDL91HVS%7CB0FDL8BW9J%7CB017BK7MD4%7CB07575FPC3&tag=tpr07-21",
  "count": 17,
  "leftOut": [
   {
    "name": "Cauliflower",
    "url": "https://www.amazon.in/s?k=fresh+cauliflower&tag=tpr07-21"
   }
  ]
 },
 "Aloo Matar": {
  "url": "https://www.amazon.in/s?k=B07BG5GZP2%7CB0FF9Z6D5D%7CB08JQTG681%7CB07BG7LB5B%7CB07BG7B7RF%7CB0GDQWH88W%7CB0DJ97QP87%7CB0BBGB4RMH%7CB079H8D8M6%7CB00LIO5JYE%7CB01B7DZ8BE%7CB017BK7MD4%7CB07BG5GJJW%7CB09WMPCGVP%7CB07575FPC3&tag=tpr07-21",
  "count": 15,
  "leftOut": []
 },
 "Bhindi Masala": {
  "url": "https://www.amazon.in/s?k=B09WGXJ8PQ%7CB07HN2W64R%7CB0752S3195%7CB079H8D8M6&tag=tpr07-21",
  "count": 4,
  "leftOut": []
 },
 "Baingan Bharta": {
  "url": "https://www.amazon.in/s?k=B07KK83WLB%7CB07HN2W64R%7CB01ABRU2JA%7CB07BG7LB5B%7CB07BG5GJJW%7CB0DJ97QP87%7CB08JQTG681%7CB00LIO5JYE%7CB003P8N772%7CB07575FPC3&tag=tpr07-21",
  "count": 10,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Mix Veg": {
  "url": "https://www.amazon.in/s?k=B08JQTG681%7CB078KT9RB1%7CB0DJ97QP87%7CB0BBGB4RMH%7CB079H8D8M6%7CB00LIO5JYE%7CB01B7DZ8BE%7CB07BG7B7RF%7CB07BG7LB5B%7CB07BG5GJJW%7CB0GDQWH88W%7CB07575FPC3&tag=tpr07-21",
  "count": 12,
  "leftOut": [
   {
    "name": "Mixed vegetables",
    "url": "https://www.amazon.in/s?k=frozen+mixed+vegetables&tag=tpr07-21"
   }
  ]
 },
 "Aloo Paratha": {
  "url": "https://www.amazon.in/s?k=B007GGTLEC%7CB09WMPCGVP%7CB07BG5GZP2%7CB00LIO5JYE%7CB01B7DZ8BE%7CB08J7QJD3T%7CB0752S3195%7CB0H1H6XH8Y%7CB07575FPC3%7CB07BG5GJJW%7CB07BG7B7RF%7CB07BG7LB5B%7CB07HN2W64R%7CB00KPSQW04&tag=tpr07-21",
  "count": 14,
  "leftOut": []
 },
 "Besan Chilla": {
  "url": "https://www.amazon.in/s?k=B0752S522F%7CB07BG68KXT%7CB07BG521JL%7CB08JQTG681%7CB0GDQWH88W%7CB07BG5GJJW%7CB07BG7LB5B%7CB07BG7B7RF%7CB07575FPC3&tag=tpr07-21",
  "count": 9,
  "leftOut": []
 },
 "Moong Dal Khichdi": {
  "url": "https://www.amazon.in/s?k=B075332XK6%7CB0BBF1FT93%7CB0FF9Z6D5D%7CB09WMPCGVP%7CB07BG7B7RF%7CB0DJ97QP87%7CB079H8D8M6%7CB0BBGB4RMH%7CB07575FPC3&tag=tpr07-21",
  "count": 9,
  "leftOut": []
 },
 "Jeera Rice": {
  "url": "https://www.amazon.in/s?k=B00YGMLWQO%7CB0DJ97QP87%7CB09WMPCGVP%7CB07HN2W64R%7CB07BG7LB5B%7CB07575FPC3&tag=tpr07-21",
  "count": 6,
  "leftOut": []
 },
 "Veg Pulao": {
  "url": "https://www.amazon.in/s?k=B0BBF1FT93%7CB07HN2W64R%7CB07BG7LB5B%7CB09GNSDZVW%7CB0DJ97QP87%7CB07BG5GZP2%7CB08FCZC99Y%7CB0D5VHYDHN%7CB01IENENPC%7CB07H2TFK5Q%7CB0FDL91HVS%7CB0FDL8BW9J%7CB0CBVMFYL9%7CB08XVX7WFX%7CB083QDBBBW%7CB09WMPCGVP%7CB07575FPC3&tag=tpr07-21",
  "count": 17,
  "leftOut": [
   {
    "name": "Mixed vegetables",
    "url": "https://www.amazon.in/s?k=frozen+mixed+vegetables&tag=tpr07-21"
   }
  ]
 },
 "Veg Biryani": {
  "url": "https://www.amazon.in/s?k=B0BBF1FT93%7CB07BG5GZP2%7CB078KT9RB1%7CB077RFB9TN%7CB07FFCGD8F%7CB07BG65QL5%7CB07BG5GJJW%7CB07BG7LB5B%7CB083QDBBBW%7CB0FBM7XTJH%7CB0DF7F726R%7CB019RL0PPW%7CB09GNV7YZM%7CB09GNSDZVW%7CB0GDQWH88W%7CB07575FPC3&tag=tpr07-21",
  "count": 16,
  "leftOut": [
   {
    "name": "Carrot",
    "url": "https://www.amazon.in/s?k=fresh+carrot&tag=tpr07-21"
   },
   {
    "name": "Cauliflower",
    "url": "https://www.amazon.in/s?k=fresh+cauliflower&tag=tpr07-21"
   }
  ]
 },
 "Pav Bhaji": {
  "url": "https://www.amazon.in/s?k=B0154VTRB2%7CB0D5VHYDHN%7CB0FF9Z6D5D%7CB01IBTCZNG%7CB0GDQWH88W%7CB0DJ97QP87%7CB07HN2W64R%7CB07BG51WMX%7CB07BG5GZP2%7CB08JQTG681%7CB07BG7B7QP%7CB07BG5GJJW%7CB01B7DZ79M%7CB00LIO5JYE%7CB079H8D8M6%7CB08H64PTLG%7CB07BG7LB5B%7CB017BK7MD4%7CB0DFLR6C1V%7CB0D2LJQCBP%7CB07575FPC3&tag=tpr07-21",
  "count": 21,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   },
   {
    "name": "Cauliflower",
    "url": "https://www.amazon.in/s?k=fresh+cauliflower&tag=tpr07-21"
   }
  ]
 },
 "Poha": {
  "url": "https://www.amazon.in/s?k=B09PDZYN2X%7CB0FF4VVGS4%7CB07HN2W64R%7CB07BG7LB5B%7CB0DFLR6C1V%7CB07BG6WKLS%7CB0DJ97QP87%7CB0FDL9B3B8%7CB08WZQ1SN3%7CB079H8D8M6%7CB0GDQWH88W%7CB07BG5GJJW%7CB00LP2LWPY%7CB07575FPC3&tag=tpr07-21",
  "count": 14,
  "leftOut": []
 },
 "Methi Thepla": {
  "url": "https://www.amazon.in/s?k=B007GGTLEC%7CB07BG7LB95%7CB077RFB9TN%7CB0GDQWH88W%7CB079H8D8M6%7CB0DJ97QP87%7CB0H1H6XH8Y%7CB01B7DZ8BE%7CB07BG7LB5B%7CB07575FPC3&tag=tpr07-21",
  "count": 10,
  "leftOut": []
 },
 "Dhokla": {
  "url": "https://www.amazon.in/s?k=B0752S522F%7CB0994VRWWW%7CB08WZQ1SN3%7CB0GDQWH88W%7CB09G96K43Z%7CB0FDL9B3B8%7CB07BG6WKLS%7CB07BG7LB5B%7CB0DFLR6C1V%7CB07BG5GJJW%7CB07BG7D7WR%7CB07575FPC3&tag=tpr07-21",
  "count": 12,
  "leftOut": []
 },
 "Masala Dosa": {
  "url": "https://www.amazon.in/s?k=B01468O5AW%7CB07BG5GZP2%7CB07HN2W64R%7CB07BG6WKLS%7CB0FDL9B3B8%7CB079H8D8M6&tag=tpr07-21",
  "count": 6,
  "leftOut": []
 },
 "Idli Sambar": {
  "url": "https://www.amazon.in/s?k=B01468O5AW%7CB074N7VHV4%7CB009LL92VC%7CB0D5VCPPNW%7CB07BG7D7WR&tag=tpr07-21",
  "count": 5,
  "leftOut": [
   {
    "name": "Mixed vegetables",
    "url": "https://www.amazon.in/s?k=frozen+mixed+vegetables&tag=tpr07-21"
   }
  ]
 },
 "Sambar Rice": {
  "url": "https://www.amazon.in/s?k=B074N7VHV4%7CB00YGMLWQO%7CB009LL92VC%7CB0D5VCPPNW%7CB07BG523CL%7CB07BG6WKLS&tag=tpr07-21",
  "count": 6,
  "leftOut": [
   {
    "name": "Mixed vegetables",
    "url": "https://www.amazon.in/s?k=frozen+mixed+vegetables&tag=tpr07-21"
   }
  ]
 },
 "Upma": {
  "url": "https://www.amazon.in/s?k=B08DRPYQT3%7CB07BG7LB5B%7CB07BG7B7RF%7CB0DFLR6C1V%7CB07HN2W64R%7CB08JQTG681%7CB09GNSDZVW%7CB07BG6WKLS%7CB077X8RBG1%7CB0BSNQFBH4%7CB0DJ97QP87%7CB0FDL9B3B8%7CB01B7DZ8BE%7CB08WZQ1SN3%7CB0GDQWH88W%7CB07575FPC3&tag=tpr07-21",
  "count": 16,
  "leftOut": []
 },
 "Margherita Pizza": {
  "url": "https://www.amazon.in/s?k=B0DG5KRNW5%7CB00O8X0GI6%7CB0BHLD142Z%7CB09NKXT8LM%7CB00X7RJSW4&tag=tpr07-21",
  "count": 5,
  "leftOut": []
 },
 "Penne Arrabbiata": {
  "url": "https://www.amazon.in/s?k=B0GX1YYY8R%7CB00X7RJSW4%7CB09NKXT8LM%7CB00LN86ZIY%7CB01GJIGZIM%7CB01B7DZ79M%7CB08JQTG681%7CB00N8KOJ88%7CB08WZQ1SN3%7CB0G4X199DK%7CB07575FPC3&tag=tpr07-21",
  "count": 11,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Pesto Pasta": {
  "url": "https://www.amazon.in/s?k=B0GX1YYY8R%7CB09NKXT8LM%7CB0G4X199DK%7CB0C65WVW3W%7CB00X7RJSW4%7CB07575FPC3&tag=tpr07-21",
  "count": 6,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Aglio e Olio": {
  "url": "https://www.amazon.in/s?k=B0GX1YYY8R%7CB00X7RJSW4%7CB00LN86ZIY%7CB07575FPC3&tag=tpr07-21",
  "count": 4,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   },
   {
    "name": "Parsley",
    "url": "https://www.amazon.in/dp/B0DPCCQXNN?tag=tpr07-21"
   }
  ]
 },
 "Mushroom Risotto": {
  "url": "https://www.amazon.in/s?k=B09BNHLLHH%7CB07BG79Z9M%7CB005LLZ2GK%7CB07HN2W64R%7CB0G4X199DK%7CB01IBTCZNG&tag=tpr07-21",
  "count": 6,
  "leftOut": []
 },
 "Veg Lasagne": {
  "url": "https://www.amazon.in/s?k=B0BWNRBL5X%7CB00X7RJSW4%7CB07HN2W64R%7CB01B7DZ79M%7CB08JQTG681%7CB00N8KOJ88%7CB00LN86ZIY%7CB01GJIGZIM%7CB08WZQ1SN3%7CB0D8FBDJ4G%7CB09NKXT8LM%7CB01IBTCZNG%7CB08DRSJGCD%7CB01IA43GSU%7CB08XVX7WFX%7CB0CGHR3KQM%7CB07BG79Z9M%7CB07BG51WMX%7CB0CB7YYH42%7CB09RGN6CW9%7CB0BHLD142Z%7CB0G4X199DK%7CB07575FPC3&tag=tpr07-21",
  "count": 23,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   },
   {
    "name": "Carrot",
    "url": "https://www.amazon.in/s?k=fresh+carrot&tag=tpr07-21"
   }
  ]
 },
 "Minestrone Soup": {
  "url": "https://www.amazon.in/s?k=B00X7RJSW4%7CB07BG51WMX%7CB07BG4XKJ5%7CB09NKXT8LM%7CB0CGHR3KQM%7CB00N8KOJ88%7CB09C3STJ24%7CB00LXSDTTC%7CB005LLZ2GK%7CB0GX1YYY8R%7CB075335G7V%7CB01GJIGZIM%7CB0D8FBDJ4G%7CB07575FPC3&tag=tpr07-21",
  "count": 14,
  "leftOut": [
   {
    "name": "Mixed vegetables",
    "url": "https://www.amazon.in/s?k=frozen+mixed+vegetables&tag=tpr07-21"
   }
  ]
 },
 "Tomato Basil Soup": {
  "url": "https://www.amazon.in/s?k=B08JQTG681%7CB00X7RJSW4%7CB0D8FBDJ4G%7CB01GJIGZIM%7CB00LN86ZIY%7CB08WZQ1SN3%7CB09NKXT8LM%7CB075335G7V%7CB077RK8L9N%7CB07575FPC3&tag=tpr07-21",
  "count": 10,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Mac and Cheese": {
  "url": "https://www.amazon.in/s?k=B0GX1YYY8R%7CB01FMCJDDA%7CB01IA43GSU%7CB01IBTCZNG%7CB08DRSJGCD&tag=tpr07-21",
  "count": 5,
  "leftOut": []
 },
 "Greek Salad": {
  "url": "https://www.amazon.in/s?k=B07BG7B7WB%7CB08JQTG681%7CB07HN2W64R%7CB07BG51WMX%7CB01MTB4BR7%7CB089F2PTFK%7CB00X7RJSW4&tag=tpr07-21",
  "count": 7,
  "leftOut": []
 },
 "Falafel & Hummus": {
  "url": "https://www.amazon.in/s?k=B0BRJ2RBMY%7CB0C431CK5Y%7CB0DFLR6C1V%7CB00X7RJSW4%7CB07HN2W64R%7CB07BG7LB5B%7CB07BG5GJJW%7CB07BG65QL5%7CB0154VT0GY%7CB00LIO5JYE%7CB01B7DZ8BE%7CB0D8FBDJ4G%7CB0C289FV4B%7CB08DRSJGCD%7CB0GDQWH88W%7CB07575FPC3&tag=tpr07-21",
  "count": 16,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   },
   {
    "name": "Pita bread",
    "url": "https://www.amazon.in/s?k=pita+bread&tag=tpr07-21"
   },
   {
    "name": "Parsley",
    "url": "https://www.amazon.in/dp/B0DPCCQXNN?tag=tpr07-21"
   },
   {
    "name": "Spring onion",
    "url": "https://www.amazon.in/dp/B07NXZWD25?tag=tpr07-21"
   }
  ]
 },
 "Veg Burrito Bowl": {
  "url": "https://www.amazon.in/s?k=B078KT9RB1%7CB07BG51WMX%7CB07HN2W64R%7CB0CP3KK885%7CB01IENENPC%7CB09GYK1DHQ%7CB08JQTG681%7CB00YGMLWQO%7CB01IBTCZNG%7CB07BG5GJJW%7CB0DFLR6C1V%7CB0CYT9FJVQ%7CB077RFB9TN%7CB09C3STJ24%7CB09H6KZYJ9%7CB07BG79ZD6%7CB07L8H6L2R%7CB07S8J2K32%7CB01FMCJDDA%7CB0GDQWH88W%7CB01B7DZ8BE%7CB0154VT0GY%7CB00LIO5JYE%7CB01GJIGZIM%7CB09BYSKVD6%7CB09BYLN5YW%7CB07575FPC3&tag=tpr07-21",
  "count": 27,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Cheese Quesadilla": {
  "url": "https://www.amazon.in/s?k=B07S8J2K32%7CB01FMCJDDA%7CB07BG51WMX%7CB0CB7YYH42%7CB07HN2W64R&tag=tpr07-21",
  "count": 5,
  "leftOut": []
 },
 "Thai Green Curry": {
  "url": "https://www.amazon.in/s?k=B081L16JTJ%7CB015QZI2LC%7CB07BG6X1S1%7CB07BG79Z9M%7CB09RGN6CW9%7CB07BG51WMX%7CB0F5PTCKYJ%7CB0BSR149NL%7CB09NKXT8LM%7CB0H1H7PWYK%7CB07575FPC3%7CB00YGMLWQO&tag=tpr07-21",
  "count": 12,
  "leftOut": [
   {
    "name": "Carrot",
    "url": "https://www.amazon.in/s?k=fresh+carrot&tag=tpr07-21"
   }
  ]
 },
 "Veg Pad Thai": {
  "url": "https://www.amazon.in/s?k=B09PKCK86L%7CB09RGN6CW9%7CB07HN2W64R%7CB0FZVWJBHR%7CB015QZI2NK%7CB00B5SLEN8%7CB09H6KX7SW%7CB0H1H7PWYK%7CB00X7RJSW4%7CB077X8MD39%7CB0FF4VVGS4%7CB07BG5GJJW%7CB0DFLR6C1V&tag=tpr07-21",
  "count": 13,
  "leftOut": [
   {
    "name": "Carrot",
    "url": "https://www.amazon.in/s?k=fresh+carrot&tag=tpr07-21"
   },
   {
    "name": "Chinese chives",
    "url": "https://www.amazon.in/dp/B07NXZWD25?tag=tpr07-21"
   }
  ]
 },
 "Veg Katsu Curry": {
  "url": "https://www.amazon.in/s?k=B0GMWG8QQM%7CB08DRSJGCD%7CB00YGMLWQO%7CB07BRMLY3C%7CB07HN2W64R%7CB07BG5GZP2&tag=tpr07-21",
  "count": 6,
  "leftOut": [
   {
    "name": "Mixed vegetables",
    "url": "https://www.amazon.in/s?k=frozen+mixed+vegetables&tag=tpr07-21"
   },
   {
    "name": "Carrot",
    "url": "https://www.amazon.in/s?k=fresh+carrot&tag=tpr07-21"
   }
  ]
 },
 "Tofu Stir-fry": {
  "url": "https://www.amazon.in/s?k=B09PKCK86L%7CB07BG79Z9M%7CB09RGN6CW9%7CB07BG6X1S1%7CB07BG51WMX%7CB0CGHR3KQM%7CB07HN2W64R%7CB07BG7LB5B%7CB09H6KX7SW%7CB0C5N1PYZB%7CB0F5PTCKYJ%7CB0D8FBDJ4G%7CB0GDQWH88W%7CB07575FPC3&tag=tpr07-21",
  "count": 14,
  "leftOut": [
   {
    "name": "Carrot",
    "url": "https://www.amazon.in/s?k=fresh+carrot&tag=tpr07-21"
   },
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Veg Hakka Noodles": {
  "url": "https://www.amazon.in/s?k=B00FHD9Y5W%7CB0GDQWH88W%7CB07HN2W64R%7CB07BG51WMX%7CB07BG521JL%7CB08WZQ1SN3%7CB07BG7LB5B%7CB00O0X7B3M%7CB09H6KX7SW%7CB0C5N1PYZB%7CB0GN3GKHB9%7CB07575FPC3&tag=tpr07-21",
  "count": 12,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   },
   {
    "name": "Carrot",
    "url": "https://www.amazon.in/s?k=fresh+carrot&tag=tpr07-21"
   },
   {
    "name": "Spring onion",
    "url": "https://www.amazon.in/dp/B07NXZWD25?tag=tpr07-21"
   }
  ]
 },
 "Veg Fried Rice": {
  "url": "https://www.amazon.in/s?k=B00YGMLWQO%7CB0GDQWH88W%7CB083QDBBBW%7CB07BG7LB5B%7CB07BG521JL%7CB07BG51WMX%7CB07BG8JPXY%7CB08WZQ1SN3%7CB078KT9RB1%7CB09H6KX7SW%7CB09H6KZYJ9%7CB0C5N1PYZB%7CB0D8FBDJ4G%7CB07575FPC3&tag=tpr07-21",
  "count": 14,
  "leftOut": [
   {
    "name": "Carrot",
    "url": "https://www.amazon.in/s?k=fresh+carrot&tag=tpr07-21"
   },
   {
    "name": "Spring onion",
    "url": "https://www.amazon.in/dp/B07NXZWD25?tag=tpr07-21"
   }
  ]
 },
 "Chilli Paneer": {
  "url": "https://www.amazon.in/s?k=B078KT9RB1%7CB075335G7V%7CB0GDQWH88W%7CB07BG7B7RF%7CB07BG7LB5B%7CB07BG51WMX%7CB08WZQ1SN3%7CB09H6KX7SW%7CB09H6KZYJ9%7CB0D8FBDJ4G%7CB07575FPC3&tag=tpr07-21",
  "count": 11,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   },
   {
    "name": "Spring onion",
    "url": "https://www.amazon.in/dp/B07NXZWD25?tag=tpr07-21"
   }
  ]
 },
 "Veg Manchurian": {
  "url": "https://www.amazon.in/s?k=B07BG521JL%7CB07BG8JPXY%7CB07BG5GJJW%7CB07BG7B7RF%7CB07BG7LB5B%7CB09H6KX7SW%7CB09H6KZYJ9%7CB01IBTCZNG%7CB00O0X7B3M%7CB08WZQ1SN3%7CB075335G7V%7CB08DRSJGCD%7CB0GDQWH88W%7CB07HN2W64R%7CB07BG51WMX%7CB0C5N1PYZB%7CB005LLZ2GK%7CB07575FPC3&tag=tpr07-21",
  "count": 18,
  "leftOut": [
   {
    "name": "Carrot",
    "url": "https://www.amazon.in/s?k=fresh+carrot&tag=tpr07-21"
   },
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   },
   {
    "name": "Spring onion",
    "url": "https://www.amazon.in/dp/B07NXZWD25?tag=tpr07-21"
   }
  ]
 },
 "Masala Omelette": {
  "url": "https://www.amazon.in/s?k=B0DG5PG3CX%7CB01IBTCZNG%7CB07HN2W64R%7CB07BG7LB5B%7CB08JQTG681%7CB07BG5GJJW%7CB07BG5GZP2%7CB0GDQWH88W%7CB0DJ97QP87%7CB07BG7B7RF%7CB079H8D8M6%7CB07575FPC3&tag=tpr07-21",
  "count": 12,
  "leftOut": [
   {
    "name": "Garlic",
    "url": "https://www.amazon.in/s?k=fresh+garlic&tag=tpr07-21"
   }
  ]
 },
 "Shakshuka": {
  "url": "https://www.amazon.in/s?k=B0DG5PG3CX%7CB09WMPCGVP%7CB07HN2W64R%7CB07BG7LB5B%7CB08JQTG681%7CB079H8D8M6%7CB01B7DZ79M%7CB00LIO5JYE%7CB017BK7MD4%7CB077RK8L9N%7CB0D8FBDJ4G%7CB077Y832Z6%7CB07575FPC3&tag=tpr07-21",
  "count": 13,
  "leftOut": []
 }
};
